const argfraTeams = [
    {
      "name": "AJ Auxerre",
      "country": "France",
      "league": "Ligue 1",
      "city": "Auxerre",
      "lat": 47.7989,
      "lon": 3.5736,
      "founded": 1905,
      "stadium": "Stade de l'Abbé-Deschamps",
      "trophies": "Ligue 1: 1, Coupe de France: 4, Ligue 2: 2",
      "mustKnowFact": "Promoted back to Ligue 1 for 2024-25 after 2022 win.",
      "active": true
    },
    {
      "name": "AS Monaco",
      "country": "France",
      "league": "Ligue 1",
      "city": "Monaco",
      "lat": 43.7333,
      "lon": 7.4167,
      "founded": 1924,
      "stadium": "Stade Louis II",
      "trophies": "Ligue 1: 8, Coupe de France: 5, Coupe de la Ligue: 1, Trophée des Champions: 4, Ligue 2: 3",
      "mustKnowFact": "Runner-up in Ligue 1 2023-24, facing PSG in 2024 Trophée.",
      "active": true
    },
    {
      "name": "AS Saint-Étienne",
      "country": "France",
      "league": "Ligue 1",
      "city": "Saint-Étienne",
      "lat": 45.4606,
      "lon": 4.3903,
      "founded": 1919,
      "stadium": "Stade Geoffroy-Guichard",
      "trophies": "Ligue 1: 10, Coupe de France: 6, Coupe de la Ligue: 1, Trophée des Champions: 5, Ligue 2: 3",
      "mustKnowFact": "Back in Ligue 1 for 2024-25 after two years.",
      "active": true
    },
    {
      "name": "Angers SCO",
      "country": "France",
      "league": "Ligue 1",
      "city": "Angers",
      "lat": 47.4656,
      "lon": -0.5558,
      "founded": 1919,
      "stadium": "Stade Raymond Kopa",
      "trophies": "Ligue 2: 2",
      "mustKnowFact": "Promoted to Ligue 1 for 2024-25.",
      "active": true
    },
    {
      "name": "Stade Brestois 29",
      "country": "France",
      "league": "Ligue 1",
      "city": "Brest",
      "lat": 48.3904,
      "lon": -4.4861,
      "founded": 1950,
      "stadium": "Stade Francis-Le Blé",
      "trophies": "Ligue 2: 2",
      "mustKnowFact": "Earned a Champions League spot in 2023-24.",
      "active": true
    },
    {
      "name": "Le Havre AC",
      "country": "France",
      "league": "Ligue 1",
      "city": "Le Havre",
      "lat": 49.4988,
      "lon": 0.1267,
      "founded": 1872,
      "stadium": "Stade Océane",
      "trophies": "Ligue 1: 0, Coupe de France: 1, Ligue 2: 6",
      "mustKnowFact": "Oldest club in France, steady in Ligue 1.",
      "active": true
    },
    {
      "name": "Lille OSC",
      "country": "France",
      "league": "Ligue 1",
      "city": "Lille",
      "lat": 50.6119,
      "lon": 3.1305,
      "founded": 1944,
      "stadium": "Stade Pierre-Mauroy",
      "trophies": "Ligue 1: 4, Coupe de France: 6, Trophée des Champions: 1, Ligue 2: 5",
      "mustKnowFact": "2021 Ligue 1 champs holding strong.",
      "active": true
    },
    {
      "name": "Montpellier HSC",
      "country": "France",
      "league": "Ligue 1",
      "city": "Montpellier",
      "lat": 43.6119,
      "lon": 3.8767,
      "founded": 1919,
      "stadium": "Stade de la Mosson",
      "trophies": "Ligue 1: 1, Coupe de France: 2, Coupe de la Ligue: 1, Ligue 2: 4",
      "mustKnowFact": "2012 Ligue 1 title remains their peak.",
      "active": true
    },
    {
      "name": "FC Nantes",
      "country": "France",
      "league": "Ligue 1",
      "city": "Nantes",
      "lat": 47.2558,
      "lon": -1.5247,
      "founded": 1943,
      "stadium": "Stade de la Beaujoire",
      "trophies": "Ligue 1: 8, Coupe de France: 4, Coupe de la Ligue: 1, Trophée des Champions: 3",
      "mustKnowFact": "Historic giants clinging to Ligue 1.",
      "active": true
    },
    {
      "name": "OGC Nice",
      "country": "France",
      "league": "Ligue 1",
      "city": "Nice",
      "lat": 43.7034,
      "lon": 7.2663,
      "founded": 1904,
      "stadium": "Allianz Riviera",
      "trophies": "Ligue 1: 4, Coupe de France: 3, Trophée des Champions: 1, Ligue 2: 4",
      "mustKnowFact": "Riviera club with INEOS backing.",
      "active": true
    },
    {
      "name": "Olympique Lyonnais",
      "country": "France",
      "league": "Ligue 1",
      "city": "Lyon",
      "lat": 45.7238,
      "lon": 4.8320,
      "founded": 1950,
      "stadium": "Groupama Stadium",
      "trophies": "Ligue 1: 7, Coupe de France: 5, Coupe de la Ligue: 1, Trophée des Champions: 8, Ligue 2: 3",
      "mustKnowFact": "Early 2000s dominance fading but still fierce.",
      "active": true
    },
    {
      "name": "Olympique Marseille",
      "country": "France",
      "league": "Ligue 1",
      "city": "Marseille",
      "lat": 43.2700,
      "lon": 5.3959,
      "founded": 1899,
      "stadium": "Stade Vélodrome",
      "trophies": "Ligue 1: 9, Champions League: 1, Coupe de France: 10, Coupe de la Ligue: 3, Trophée des Champions: 3, Ligue 2: 1",
      "mustKnowFact": "France's only Champions League winner (1993).",
      "active": true
    },
    {
      "name": "Paris Saint-Germain",
      "country": "France",
      "league": "Ligue 1",
      "city": "Paris",
      "lat": 48.8414,
      "lon": 2.2530,
      "founded": 1970,
      "stadium": "Parc des Princes",
      "trophies": "Ligue 1: 12, Coupe de France: 15, Coupe de la Ligue: 10, Trophée des Champions: 12, Ligue 2: 1, UEFA Cup Winners' Cup: 1",
      "mustKnowFact": "2024 Trophée des Champions winners over Monaco.",
      "active": true
    },
    {
      "name": "RC Lens",
      "country": "France",
      "league": "Ligue 1",
      "city": "Lens",
      "lat": 50.4322,
      "lon": 2.8318,
      "founded": 1906,
      "stadium": "Stade Bollaert-Delelis",
      "trophies": "Ligue 1: 1, Coupe de la Ligue: 1, Ligue 2: 4",
      "mustKnowFact": "Coal town's red-and-yellow resurgence.",
      "active": true
    },
    {
      "name": "Stade Rennais",
      "country": "France",
      "league": "Ligue 1",
      "city": "Rennes",
      "lat": 48.1147,
      "lon": -1.6794,
      "founded": 1901,
      "stadium": "Roazhon Park",
      "trophies": "Coupe de France: 3, Ligue 2: 2, Trophée des Champions: 1",
      "mustKnowFact": "Brittany's consistent European contenders.",
      "active": true
    },
    {
      "name": "Stade de Reims",
      "country": "France",
      "league": "Ligue 1",
      "city": "Reims",
      "lat": 49.2500,
      "lon": 4.0333,
      "founded": 1931,
      "stadium": "Stade Auguste-Delaune",
      "trophies": "Ligue 1: 6, Coupe de France: 2, Trophée des Champions: 4, Ligue 2: 2",
      "mustKnowFact": "1950s European finalists reborn.",
      "active": true
    },
    {
      "name": "RC Strasbourg Alsace",
      "country": "France",
      "league": "Ligue 1",
      "city": "Strasbourg",
      "lat": 48.5846,
      "lon": 7.7360,
      "founded": 1906,
      "stadium": "Stade de la Meinau",
      "trophies": "Ligue 1: 1, Coupe de France: 3, Coupe de la Ligue: 3, Ligue 2: 1",
      "mustKnowFact": "Alsace's blue-and-white pride.",
      "active": true
    },
    {
      "name": "Toulouse FC",
      "country": "France",
      "league": "Ligue 1",
      "city": "Toulouse",
      "lat": 43.5832,
      "lon": 1.4340,
      "founded": 1937,
      "stadium": "Stadium de Toulouse",
      "trophies": "Coupe de France: 2, Ligue 2: 4",
      "mustKnowFact": "2023 Coupe de France champs.",
      "active": true
    },
    {
      "name": "Argentinos Juniors",
      "country": "Argentina",
      "league": "Primera División",
      "city": "Buenos Aires",
      "lat": -34.6076,
      "lon": -58.4472,
      "founded": 1904,
      "stadium": "Estadio Diego Armando Maradona",
      "trophies": "Primera División: 3, Copa Libertadores: 1, Copa Interamericana: 1",
      "mustKnowFact": "Maradona's launchpad.",
      "active": true
    },
    {
      "name": "Atlético Tucumán",
      "country": "Argentina",
      "league": "Primera División",
      "city": "San Miguel de Tucumán",
      "lat": -26.8083,
      "lon": -65.2176,
      "founded": 1902,
      "stadium": "Estadio Monumental José Fierro",
      "trophies": "Primera B Nacional: 2",
      "mustKnowFact": "Tucumán's northern giants.",
      "active": true
    },
    {
      "name": "Banfield",
      "country": "Argentina",
      "league": "Primera División",
      "city": "Banfield",
      "lat": -34.7490,
      "lon": -58.3879,
      "founded": 1896,
      "stadium": "Estadio Florencio Sola",
      "trophies": "Primera División: 1, Primera B Nacional: 3",
      "mustKnowFact": "The Drill's southern grit.",
      "active": true
    },
    {
      "name": "Barracas Central",
      "country": "Argentina",
      "league": "Primera División",
      "city": "Buenos Aires",
      "lat": -34.6417,
      "lon": -58.3881,
      "founded": 1904,
      "stadium": "Estadio Claudio Chiqui Tapia",
      "trophies": "Primera B Metropolitana: 1",
      "mustKnowFact": "Buenos Aires barrio climbers.",
      "active": true
    },
    {
      "name": "Belgrano",
      "country": "Argentina",
      "league": "Primera División",
      "city": "Córdoba",
      "lat": -31.4167,
      "lon": -64.1833,
      "founded": 1905,
      "stadium": "Estadio Julio César Villagra",
      "trophies": "Primera B Nacional: 2",
      "mustKnowFact": "Córdoba's pirate crew.",
      "active": true
    },
    {
      "name": "Boca Juniors",
      "country": "Argentina",
      "league": "Primera División",
      "city": "Buenos Aires",
      "lat": -34.6355,
      "lon": -58.3648,
      "founded": 1905,
      "stadium": "La Bombonera",
      "trophies": "Primera División: 35, Copa Libertadores: 6, Intercontinental Cup: 3, Copa Sudamericana: 2, Recopa Sudamericana: 4, Copa Argentina: 4, Supercopa Argentina: 2",
      "mustKnowFact": "La Bombonera shakes with passion.",
      "active": true
    },
    {
      "name": "Central Córdoba SdE",
      "country": "Argentina",
      "league": "Primera División",
      "city": "Santiago del Estero",
      "lat": -27.7833,
      "lon": -64.2667,
      "founded": 1919,
      "stadium": "Estadio Alfredo Terrera",
      "trophies": "Primera B Nacional: 1",
      "mustKnowFact": "Railway roots in Santiago.",
      "active": true
    },
    {
      "name": "Defensa y Justicia",
      "country": "Argentina",
      "league": "Primera División",
      "city": "Florencio Varela",
      "lat": -34.8167,
      "lon": -58.2833,
      "founded": 1935,
      "stadium": "Estadio Norberto Tito Tomaghello",
      "trophies": "Copa Sudamericana: 1, Recopa Sudamericana: 1, Primera B Nacional: 1",
      "mustKnowFact": "Small club, massive 2020 Copa win.",
      "active": true
    },
    {
      "name": "Deportivo Riestra",
      "country": "Argentina",
      "league": "Primera División",
      "city": "Buenos Aires",
      "lat": -34.6667,
      "lon": -58.4667,
      "founded": 1931,
      "stadium": "Estadio Guillermo Laza",
      "trophies": "Primera B Metropolitana: 1",
      "mustKnowFact": "Primera debutants in 2024.",
      "active": true
    },
    {
      "name": "Estudiantes de La Plata",
      "country": "Argentina",
      "league": "Primera División",
      "city": "La Plata",
      "lat": -34.9137,
      "lon": -57.9391,
      "founded": 1905,
      "stadium": "Estadio Jorge Luis Hirschi",
      "trophies": "Primera División: 6, Copa Libertadores: 4, Intercontinental Cup: 1, Copa Argentina: 1",
      "mustKnowFact": "1960s global conquerors.",
      "active": true
    },
    {
      "name": "Gimnasia y Esgrima La Plata",
      "country": "Argentina",
      "league": "Primera División",
      "city": "La Plata",
      "lat": -34.9205,
      "lon": -57.9916,
      "founded": 1887,
      "stadium": "Estadio Juan Carmelo Zerillo",
      "trophies": "Primera División: 1, Copa Centenario: 1",
      "mustKnowFact": "Oldest club in Argentina.",
      "active": true
    },
    {
      "name": "Godoy Cruz",
      "country": "Argentina",
      "league": "Primera División",
      "city": "Mendoza",
      "lat": -32.8895,
      "lon": -68.8440,
      "founded": 1921,
      "stadium": "Estadio Malvinas Argentinas",
      "trophies": "Primera B Nacional: 1",
      "mustKnowFact": "Mendoza's football heartbeat.",
      "active": true
    },
    {
      "name": "Huracán",
      "country": "Argentina",
      "league": "Primera División",
      "city": "Buenos Aires",
      "lat": -34.6431,
      "lon": -58.3976,
      "founded": 1908,
      "stadium": "Estadio Tomás Adolfo Ducó",
      "trophies": "Primera División: 5",
      "mustKnowFact": "The Balloon flies in Parque Patricios.",
      "active": true
    },
    {
      "name": "Independiente",
      "country": "Argentina",
      "league": "Primera División",
      "city": "Avellaneda",
      "lat": -34.6703,
      "lon": -58.3710,
      "founded": 1905,
      "stadium": "Estadio Libertadores de América",
      "trophies": "Primera División: 16, Copa Libertadores: 7, Intercontinental Cup: 2, Copa Sudamericana: 2, Recopa Sudamericana: 1, Supercopa Libertadores: 1",
      "mustKnowFact": "Record seven Libertadores titles.",
      "active": true
    },
    {
      "name": "Instituto ACC",
      "country": "Argentina",
      "league": "Primera División",
      "city": "Córdoba",
      "lat": -31.4167,
      "lon": -64.1833,
      "founded": 1918,
      "stadium": "Estadio Juan Domingo Perón",
      "trophies": "Primera B Nacional: 2",
      "mustKnowFact": "Córdoba's academic fighters.",
      "active": true
    },
    {
      "name": "Lanús",
      "country": "Argentina",
      "league": "Primera División",
      "city": "Lanús",
      "lat": -34.7172,
      "lon": -58.3849,
      "founded": 1915,
      "stadium": "Estadio Ciudad de Lanús",
      "trophies": "Primera División: 2, Copa Sudamericana: 1, Supercopa Argentina: 1, Primera B Nacional: 1",
      "mustKnowFact": "Granate's suburban success.",
      "active": true
    },
    {
      "name": "Newell's Old Boys",
      "country": "Argentina",
      "league": "Primera División",
      "city": "Rosario",
      "lat": -32.9476,
      "lon": -60.6665,
      "founded": 1903,
      "stadium": "Estadio Marcelo Bielsa",
      "trophies": "Primera División: 6, Primera B Nacional: 1",
      "mustKnowFact": "Messi's childhood heroes.",
      "active": true
    },
    {
      "name": "Platense",
      "country": "Argentina",
      "league": "Primera División",
      "city": "Buenos Aires",
      "lat": -34.5833,
      "lon": -58.4167,
      "founded": 1905,
      "stadium": "Estadio Ciudad de Vicente López",
      "trophies": "Primera B Metropolitana: 1",
      "mustKnowFact": "The Squid's steady rise.",
      "active": true
    },
    {
      "name": "Racing Club",
      "country": "Argentina",
      "league": "Primera División",
      "city": "Avellaneda",
      "lat": -34.6675,
      "lon": -58.3686,
      "founded": 1903,
      "stadium": "Estadio Presidente Perón",
      "trophies": "Primera División: 18, Copa Libertadores: 1, Intercontinental Cup: 1, Supercopa Argentina: 1",
      "mustKnowFact": "The Academy's trophy-laden history.",
      "active": true
    },
    {
      "name": "River Plate",
      "country": "Argentina",
      "league": "Primera División",
      "city": "Buenos Aires",
      "lat": -34.5453,
      "lon": -58.4498,
      "founded": 1901,
      "stadium": "Estadio Monumental",
      "trophies": "Primera División: 38, Copa Libertadores: 4, Intercontinental Cup: 1, Copa Sudamericana: 1, Recopa Sudamericana: 3, Supercopa Argentina: 3, Copa Argentina: 3",
      "mustKnowFact": "Argentina's trophy kings.",
      "active": true
    },
    {
      "name": "Rosario Central",
      "country": "Argentina",
      "league": "Primera División",
      "city": "Rosario",
      "lat": -32.9507,
      "lon": -60.6665,
      "founded": 1889,
      "stadium": "Estadio Gigante de Arroyito",
      "trophies": "Primera División: 4, Copa CONMEBOL: 1, Copa Argentina: 1, Primera B Nacional: 2",
      "mustKnowFact": "Rosario's blue-and-yellow soul.",
      "active": true
    },
    {
      "name": "San Lorenzo",
      "country": "Argentina",
      "league": "Primera División",
      "city": "Buenos Aires",
      "lat": -34.6372,
      "lon": -58.4029,
      "founded": 1908,
      "stadium": "Estadio Pedro Bidegain",
      "trophies": "Primera División: 15, Copa Libertadores: 1, Copa Sudamericana: 1, Supercopa Argentina: 1",
      "mustKnowFact": "Pope Francis cheers for them.",
      "active": true
    },
    {
      "name": "Sarmiento",
      "country": "Argentina",
      "league": "Primera División",
      "city": "Junín",
      "lat": -34.5833,
      "lon": -60.9500,
      "founded": 1911,
      "stadium": "Estadio Eva Perón",
      "trophies": "Primera B Nacional: 1",
      "mustKnowFact": "Junín's green resilience.",
      "active": true
    },
    {
      "name": "Talleres",
      "country": "Argentina",
      "league": "Primera División",
      "city": "Córdoba",
      "lat": -31.4167,
      "lon": -64.1833,
      "founded": 1913,
      "stadium": "Estadio Mario Alberto Kempes",
      "trophies": "Primera División: 1, Copa CONMEBOL: 1, Primera B Nacional: 2",
      "mustKnowFact": "Córdoba's modern power.",
      "active": true
    },
    {
      "name": "Tigre",
      "country": "Argentina",
      "league": "Primera División",
      "city": "Victoria",
      "lat": -34.4167,
      "lon": -58.5833,
      "founded": 1902,
      "stadium": "Estadio José Dellagiovanna",
      "trophies": "Primera B Nacional: 3",
      "mustKnowFact": "Tiger stripes near Buenos Aires.",
      "active": true
    },
    {
      "name": "Unión",
      "country": "Argentina",
      "league": "Primera División",
      "city": "Santa Fe",
      "lat": -31.6333,
      "lon": -60.7000,
      "founded": 1907,
      "stadium": "Estadio 15 de Abril",
      "trophies": "Primera B Nacional: 1",
      "mustKnowFact": "Santa Fe's red-and-white faithful.",
      "active": true
    },
    {
      "name": "Vélez Sarsfield",
      "country": "Argentina",
      "league": "Primera División",
      "city": "Buenos Aires",
      "lat": -34.6350,
      "lon": -58.5228,
      "founded": 1910,
      "stadium": "Estadio José Amalfitani",
      "trophies": "Primera División: 10, Copa Libertadores: 1, Intercontinental Cup: 1, Copa Interamericana: 1, Supercopa Argentina: 1, Recopa Sudamericana: 1",
      "mustKnowFact": "Fortín's blue-and-white fortress.",
      "active": true
    }
  ];