const teams = [
    {
        "name": "Real Madrid",
        "country": "Spain",
        "league": "La Liga",
        "city": "Madrid",
        "lat": 40.4168,
        "lon": -3.7038,
        "founded": 1902,
        "stadium": "Santiago Bernabeu",
        "trophies": "La Liga: 35, Champions League: 14, Copa del Rey: 20, Club World Cup: 8",
        "mustKnowFact": "Most Champions League titles in history.",
        "active": true,
        "logo": "logos/real_madrid.png",
        "uniform": "uniforms/real_madrid.png"
    },
    {
        "name": "Barcelona",
        "country": "Spain",
        "league": "La Liga",
        "city": "Barcelona",
        "lat": 41.3851,
        "lon": 2.1734,
        "founded": 1899,
        "stadium": "Camp Nou",
        "trophies": "La Liga: 27, Champions League: 5, Copa del Rey: 31, Club World Cup: 3",
        "mustKnowFact": "Messi\u00e2\u20ac\u2122s legendary career began here.",
        "active": true,
        "logo": "logos/barcelona.png",
        "uniform": "uniforms/barcelona.png"
    },
    {
        "name": "Atletico Madrid",
        "country": "Spain",
        "league": "La Liga",
        "city": "Madrid",
        "lat": 40.436,
        "lon": -3.5996,
        "founded": 1903,
        "stadium": "Wanda Metropolitano",
        "trophies": "La Liga: 11, Europa League: 3, Copa del Rey: 10, UEFA Super Cup: 3",
        "mustKnowFact": "Simeone turned them into giants.",
        "active": true,
        "logo": "logos/atletico_madrid.png",
        "uniform": "uniforms/atletico_madrid.png"
    },
    {
        "name": "Real Sociedad",
        "country": "Spain",
        "league": "La Liga",
        "city": "San Sebastian",
        "lat": 43.3183,
        "lon": -1.9812,
        "founded": 1909,
        "stadium": "Reale Arena",
        "trophies": "La Liga: 2, Copa del Rey: 3",
        "mustKnowFact": "Basque pride runs deep.",
        "active": true,
        "logo": "logos/real_sociedad.png",
        "uniform": "uniforms/real_sociedad.png"
    },
    {
        "name": "Villarreal",
        "country": "Spain",
        "league": "La Liga",
        "city": "Villarreal",
        "lat": 39.9442,
        "lon": -0.1035,
        "founded": 1923,
        "stadium": "Estadio de la Ceramica",
        "trophies": "Europa League: 1",
        "mustKnowFact": "The Yellow Submarine shocked Europe.",
        "active": true,
        "logo": "logos/villarreal.png",
        "uniform": "uniforms/villarreal.png"
    },
    {
        "name": "Real Betis",
        "country": "Spain",
        "league": "La Liga",
        "city": "Seville",
        "lat": 37.3891,
        "lon": -5.9845,
        "founded": 1907,
        "stadium": "Benito Villamarin",
        "trophies": "La Liga: 1, Copa del Rey: 3",
        "mustKnowFact": "Green and white fervor.",
        "active": true,
        "logo": "logos/real_betis.png",
        "uniform": "uniforms/real_betis.png"
    },
    {
        "name": "Sevilla",
        "country": "Spain",
        "league": "La Liga",
        "city": "Seville",
        "lat": 37.3891,
        "lon": -5.9845,
        "founded": 1890,
        "stadium": "Ramon Sanchez Pizjuan",
        "trophies": "La Liga: 1, Europa League: 7, Copa del Rey: 5",
        "mustKnowFact": "Europa League masters.",
        "active": true,
        "logo": "logos/sevilla.png",
        "uniform": "uniforms/sevilla.png"
    },
    {
        "name": "Athletic Bilbao",
        "country": "Spain",
        "league": "La Liga",
        "city": "Bilbao",
        "lat": 43.263,
        "lon": -2.934,
        "founded": 1898,
        "stadium": "San Mames",
        "trophies": "La Liga: 8, Copa del Rey: 23",
        "mustKnowFact": "Only signs Basque players.",
        "active": true,
        "logo": "logos/athletic_bilbao.png",
        "uniform": "uniforms/athletic_bilbao.png"
    },
    {
        "name": "Valencia",
        "country": "Spain",
        "league": "La Liga",
        "city": "Valencia",
        "lat": 39.4699,
        "lon": -0.3763,
        "founded": 1919,
        "stadium": "Mestalla",
        "trophies": "La Liga: 6, Copa del Rey: 8, Europa League: 1",
        "mustKnowFact": "The bat logo is iconic.",
        "active": true,
        "logo": "logos/valencia.png",
        "uniform": "uniforms/valencia.png"
    },
    {
        "name": "Getafe",
        "country": "Spain",
        "league": "La Liga",
        "city": "Getafe",
        "lat": 40.3083,
        "lon": -3.7328,
        "founded": 1983,
        "stadium": "Coliseum Alfonso Perez",
        "trophies": "",
        "mustKnowFact": "Madrid\u00e2\u20ac\u2122s gritty underdogs.",
        "active": true,
        "logo": "logos/getafe.png",
        "uniform": "uniforms/getafe.png"
    },
    {
        "name": "Celta Vigo",
        "country": "Spain",
        "league": "La Liga",
        "city": "Vigo",
        "lat": 42.2406,
        "lon": -8.7207,
        "founded": 1923,
        "stadium": "Balaidos",
        "trophies": "",
        "mustKnowFact": "Galician tenacity shines.",
        "active": true,
        "logo": "logos/celta_vigo.png",
        "uniform": "uniforms/celta_vigo.png"
    },
    {
        "name": "Osasuna",
        "country": "Spain",
        "league": "La Liga",
        "city": "Pamplona",
        "lat": 42.8188,
        "lon": -1.6458,
        "founded": 1920,
        "stadium": "El Sadar",
        "trophies": "",
        "mustKnowFact": "Navarre\u00e2\u20ac\u2122s red warriors.",
        "active": true,
        "logo": "logos/osasuna.png",
        "uniform": "uniforms/osasuna.png"
    },
    {
        "name": "Girona",
        "country": "Spain",
        "league": "La Liga",
        "city": "Girona",
        "lat": 41.9794,
        "lon": 2.8214,
        "founded": 1930,
        "stadium": "Montilivi",
        "trophies": "",
        "mustKnowFact": "City Football Group\u00e2\u20ac\u2122s Catalan star.",
        "active": true,
        "logo": "logos/girona.png",
        "uniform": "uniforms/girona.png"
    },
    {
        "name": "Rayo Vallecano",
        "country": "Spain",
        "league": "La Liga",
        "city": "Madrid",
        "lat": 40.3919,
        "lon": -3.6588,
        "founded": 1924,
        "stadium": "Vallecas",
        "trophies": "",
        "mustKnowFact": "Vallecas\u00e2\u20ac\u2122 working-class heroes.",
        "active": true,
        "logo": "https://via.placeholder.com/200?text=Logo",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Mallorca",
        "country": "Spain",
        "league": "La Liga",
        "city": "Palma",
        "lat": 39.5696,
        "lon": 2.6502,
        "founded": 1916,
        "stadium": "Son Moix",
        "trophies": "Copa del Rey: 1",
        "mustKnowFact": "Island grit in La Liga.",
        "active": true,
        "logo": "logos/mallorca.png",
        "uniform": "uniforms/mallorca.png"
    },
    {
        "name": "Espanyol",
        "country": "Spain",
        "league": "La Liga",
        "city": "Barcelona",
        "lat": 41.3478,
        "lon": 2.0757,
        "founded": 1900,
        "stadium": "RCDE Stadium",
        "trophies": "Copa del Rey: 4",
        "mustKnowFact": "Barcelona\u00e2\u20ac\u2122s quieter rival.",
        "active": true,
        "logo": "logos/espanyol.png",
        "uniform": "uniforms/espanyol.png"
    },
    {
        "name": "Alaves",
        "country": "Spain",
        "league": "La Liga",
        "city": "Vitoria-Gasteiz",
        "lat": 42.8506,
        "lon": -2.6724,
        "founded": 1921,
        "stadium": "Mendizorrotza",
        "trophies": "",
        "mustKnowFact": "Basque underdogs punch above.",
        "active": true,
        "logo": "logos/alaves.png",
        "uniform": "uniforms/alaves.png"
    },
    {
        "name": "Leganes",
        "country": "Spain",
        "league": "La Liga",
        "city": "Leganes",
        "lat": 40.3302,
        "lon": -3.768,
        "founded": 1928,
        "stadium": "Butarque",
        "trophies": "",
        "mustKnowFact": "Madrid\u00e2\u20ac\u2122s southern minnows.",
        "active": true,
        "logo": "logos/leganes.png",
        "uniform": "uniforms/leganes.png"
    },
    {
        "name": "Real Valladolid",
        "country": "Spain",
        "league": "La Liga",
        "city": "Valladolid",
        "lat": 41.6523,
        "lon": -4.7245,
        "founded": 1928,
        "stadium": "Jose Zorrilla",
        "trophies": "",
        "mustKnowFact": "Ronaldo\u00e2\u20ac\u2122s ownership dream.",
        "active": true,
        "logo": "logos/real_valladolid.png",
        "uniform": "uniforms/real_valladolid.png"
    },
    {
        "name": "Las Palmas",
        "country": "Spain",
        "league": "La Liga",
        "city": "Las Palmas",
        "lat": 28.1235,
        "lon": -15.4363,
        "founded": 1949,
        "stadium": "Gran Canaria",
        "trophies": "",
        "mustKnowFact": "Canary Islands\u00e2\u20ac\u2122 sunny flair.",
        "active": true,
        "logo": "logos/las_palmas.png",
        "uniform": "uniforms/las_palmas.png"
    },
    {
        "name": "Manchester United",
        "country": "England",
        "league": "Premier League",
        "city": "Manchester",
        "lat": 53.4831,
        "lon": -2.2446,
        "founded": 1878,
        "stadium": "Old Trafford",
        "trophies": "Premier League: 13, First Division: 7, Champions League: 3, FA Cup: 12",
        "mustKnowFact": "Global fanbase giants.",
        "active": true,
        "logo": "logos/manchester_united.png",
        "uniform": "uniforms/manchester_united.png"
    },
    {
        "name": "Manchester City",
        "country": "England",
        "league": "Premier League",
        "city": "Manchester",
        "lat": 53.483,
        "lon": -2.2004,
        "founded": 1880,
        "stadium": "Etihad Stadium",
        "trophies": "Premier League: 10, FA Cup: 7, League Cup: 8, Champions League: 1",
        "mustKnowFact": "Pep\u00e2\u20ac\u2122s tactical revolution.",
        "active": true,
        "logo": "logos/manchester_city.png",
        "uniform": "uniforms/manchester_city.png"
    },
    {
        "name": "Liverpool",
        "country": "England",
        "league": "Premier League",
        "city": "Liverpool",
        "lat": 53.4308,
        "lon": -2.9608,
        "founded": 1892,
        "stadium": "Anfield",
        "trophies": "Premier League: 1, First Division: 18, Champions League: 6, FA Cup: 8",
        "mustKnowFact": "You\u00e2\u20ac\u2122ll Never Walk Alone anthem.",
        "active": true,
        "logo": "logos/liverpool.png",
        "uniform": "uniforms/liverpool.png"
    },
    {
        "name": "Chelsea",
        "country": "England",
        "league": "Premier League",
        "city": "London",
        "lat": 51.4816,
        "lon": -0.191,
        "founded": 1905,
        "stadium": "Stamford Bridge",
        "trophies": "Premier League: 6, Champions League: 2, FA Cup: 8, Europa League: 2",
        "mustKnowFact": "Abramovich\u00e2\u20ac\u2122s trophy era.",
        "active": true,
        "logo": "logos/chelsea.png",
        "uniform": "uniforms/chelsea.png"
    },
    {
        "name": "Arsenal",
        "country": "England",
        "league": "Premier League",
        "city": "London",
        "lat": 51.5549,
        "lon": -0.1084,
        "founded": 1886,
        "stadium": "Emirates Stadium",
        "trophies": "Premier League: 3, First Division: 10, FA Cup: 14",
        "mustKnowFact": "The Invincibles of 2003-04.",
        "active": true,
        "logo": "logos/arsenal.png",
        "uniform": "uniforms/arsenal.png"
    },
    {
        "name": "Tottenham Hotspur",
        "country": "England",
        "league": "Premier League",
        "city": "London",
        "lat": 51.6032,
        "lon": -0.0657,
        "founded": 1882,
        "stadium": "Tottenham Hotspur Stadium",
        "trophies": "First Division: 2, FA Cup: 8, League Cup: 4, UEFA Cup: 2",
        "mustKnowFact": "New stadium, big dreams.",
        "active": true,
        "logo": "logos/tottenham_hotspur.png",
        "uniform": "uniforms/tottenham_hotspur.png"
    },
    {
        "name": "Newcastle United",
        "country": "England",
        "league": "Premier League",
        "city": "Newcastle",
        "lat": 54.9756,
        "lon": -1.6216,
        "founded": 1892,
        "stadium": "St James\u00e2\u20ac\u2122 Park",
        "trophies": "First Division: 4, FA Cup: 6",
        "mustKnowFact": "Geordie passion runs wild.",
        "active": true,
        "logo": "logos/newcastle_united.png",
        "uniform": "uniforms/newcastle_united.png"
    },
    {
        "name": "Aston Villa",
        "country": "England",
        "league": "Premier League",
        "city": "Birmingham",
        "lat": 52.5091,
        "lon": -1.8848,
        "founded": 1874,
        "stadium": "Villa Park",
        "trophies": "First Division: 7, Champions League: 1, FA Cup: 7",
        "mustKnowFact": "1982 European champs.",
        "active": true,
        "logo": "logos/aston_villa.png",
        "uniform": "uniforms/aston_villa.png"
    },
    {
        "name": "West Ham United",
        "country": "England",
        "league": "Premier League",
        "city": "London",
        "lat": 51.5319,
        "lon": 0.0394,
        "founded": 1895,
        "stadium": "London Stadium",
        "trophies": "FA Cup: 3, Conference League: 1",
        "mustKnowFact": "Hammers conquered Europe in 2023.",
        "active": true,
        "logo": "logos/west_ham_united.png",
        "uniform": "uniforms/west_ham_united.png"
    },
    {
        "name": "Everton",
        "country": "England",
        "league": "Premier League",
        "city": "Liverpool",
        "lat": 53.4388,
        "lon": -2.9663,
        "founded": 1878,
        "stadium": "Goodison Park",
        "trophies": "First Division: 9, FA Cup: 5",
        "mustKnowFact": "Toffees\u00e2\u20ac\u2122 historic Goodison.",
        "active": true,
        "logo": "logos/everton.png",
        "uniform": "uniforms/everton.png"
    },
    {
        "name": "Brighton & Hove Albion",
        "country": "England",
        "league": "Premier League",
        "city": "Brighton",
        "lat": 50.8294,
        "lon": -0.1391,
        "founded": 1901,
        "stadium": "Amex Stadium",
        "trophies": "",
        "mustKnowFact": "Seagulls soaring in style.",
        "active": true,
        "logo": "https://via.placeholder.com/200?text=Logo",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Wolverhampton Wanderers",
        "country": "England",
        "league": "Premier League",
        "city": "Wolverhampton",
        "lat": 52.5902,
        "lon": -2.1305,
        "founded": 1877,
        "stadium": "Molineux",
        "trophies": "First Division: 3, FA Cup: 4, League Cup: 2",
        "mustKnowFact": "Wolves\u00e2\u20ac\u2122 golden old days.",
        "active": true,
        "logo": "https://via.placeholder.com/200?text=Logo",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Crystal Palace",
        "country": "England",
        "league": "Premier League",
        "city": "London",
        "lat": 51.3983,
        "lon": -0.0855,
        "founded": 1905,
        "stadium": "Selhurst Park",
        "trophies": "",
        "mustKnowFact": "Eagles of Selhurst soar.",
        "active": true,
        "logo": "logos/crystal_palace.png",
        "uniform": "uniforms/crystal_palace.png"
    },
    {
        "name": "Brentford",
        "country": "England",
        "league": "Premier League",
        "city": "London",
        "lat": 51.4882,
        "lon": -0.3048,
        "founded": 1889,
        "stadium": "Gtech Community Stadium",
        "trophies": "",
        "mustKnowFact": "Bees buzz in the top flight.",
        "active": true,
        "logo": "logos/brentford.png",
        "uniform": "uniforms/brentford.png"
    },
    {
        "name": "Nottingham Forest",
        "country": "England",
        "league": "Premier League",
        "city": "Nottingham",
        "lat": 52.94,
        "lon": -1.137,
        "founded": 1865,
        "stadium": "City Ground",
        "trophies": "First Division: 1, Champions League: 2, FA Cup: 2",
        "mustKnowFact": "Back-to-back European champs.",
        "active": true,
        "logo": "logos/nottingham_forest.png",
        "uniform": "uniforms/nottingham_forest.png"
    },
    {
        "name": "Bournemouth",
        "country": "England",
        "league": "Premier League",
        "city": "Bournemouth",
        "lat": 50.7352,
        "lon": -1.838,
        "founded": 1899,
        "stadium": "Vitality Stadium",
        "trophies": "",
        "mustKnowFact": "Cherries\u00e2\u20ac\u2122 coastal comeback.",
        "active": true,
        "logo": "logos/bournemouth.png",
        "uniform": "uniforms/bournemouth.png"
    },
    {
        "name": "Fulham",
        "country": "England",
        "league": "Premier League",
        "city": "London",
        "lat": 51.475,
        "lon": -0.2216,
        "founded": 1879,
        "stadium": "Craven Cottage",
        "trophies": "",
        "mustKnowFact": "Riverside charm lives on.",
        "active": true,
        "logo": "logos/fulham.png",
        "uniform": "uniforms/fulham.png"
    },
    {
        "name": "Southampton",
        "country": "England",
        "league": "Premier League",
        "city": "Southampton",
        "lat": 50.9059,
        "lon": -1.391,
        "founded": 1885,
        "stadium": "St Mary\u00e2\u20ac\u2122s",
        "trophies": "FA Cup: 1",
        "mustKnowFact": "Saints march back up.",
        "active": true,
        "logo": "logos/southampton.png",
        "uniform": "uniforms/southampton.png"
    },
    {
        "name": "Leicester City",
        "country": "England",
        "league": "Premier League",
        "city": "Leicester",
        "lat": 52.6203,
        "lon": -1.1422,
        "founded": 1884,
        "stadium": "King Power Stadium",
        "trophies": "Premier League: 1, FA Cup: 1, League Cup: 3",
        "mustKnowFact": "2016\u00e2\u20ac\u2122s fairy-tale champs.",
        "active": true,
        "logo": "logos/leicester_city.png",
        "uniform": "uniforms/leicester_city.png"
    },
    {
        "name": "Ipswich Town",
        "country": "England",
        "league": "Premier League",
        "city": "Ipswich",
        "lat": 52.055,
        "lon": 1.145,
        "founded": 1878,
        "stadium": "Portman Road",
        "trophies": "First Division: 1, FA Cup: 1, UEFA Cup: 1",
        "mustKnowFact": "Tractor Boys return.",
        "active": true,
        "logo": "logos/ipswich_town.png",
        "uniform": "uniforms/ipswich_town.png"
    },
    {
        "name": "Flamengo",
        "country": "Brazil",
        "league": "Serie A",
        "city": "Rio de Janeiro",
        "lat": -22.9083,
        "lon": -43.1964,
        "founded": 1895,
        "stadium": "Maracana",
        "trophies": "Serie A: 8, Copa Libertadores: 3, Copa do Brasil: 4",
        "mustKnowFact": "Brazil\u00e2\u20ac\u2122s most popular club.",
        "active": true,
        "logo": "logos/flamengo.png",
        "uniform": "uniforms/flamengo.png"
    },
    {
        "name": "Palmeiras",
        "country": "Brazil",
        "league": "Serie A",
        "city": "Sao Paulo",
        "lat": -23.5489,
        "lon": -46.6388,
        "founded": 1914,
        "stadium": "Allianz Parque",
        "trophies": "Serie A: 11, Copa Libertadores: 3, Copa do Brasil: 4",
        "mustKnowFact": "First club world champs.",
        "active": true,
        "logo": "logos/palmeiras.png",
        "uniform": "uniforms/palmeiras.png"
    },
    {
        "name": "Santos FC",
        "country": "Brazil",
        "league": "Serie A",
        "city": "Santos",
        "lat": -23.5505,
        "lon": -46.6333,
        "founded": 1912,
        "stadium": "Vila Belmiro",
        "trophies": "Serie A: 7, Copa Libertadores: 3, Copa do Brasil: 1",
        "mustKnowFact": "Pele\u00e2\u20ac\u2122s iconic home.",
        "active": true,
        "logo": "https://via.placeholder.com/200?text=Logo",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Corinthians",
        "country": "Brazil",
        "league": "Serie A",
        "city": "Sao Paulo",
        "lat": -23.5453,
        "lon": -46.4731,
        "founded": 1910,
        "stadium": "Neo Quimica Arena",
        "trophies": "Serie A: 7, Copa Libertadores: 1, Copa do Brasil: 3",
        "mustKnowFact": "Tim\u00c3\u00a3o\u00e2\u20ac\u2122s loyal army.",
        "active": true,
        "logo": "logos/corinthians.png",
        "uniform": "uniforms/corinthians.png"
    },
    {
        "name": "Sao Paulo",
        "country": "Brazil",
        "league": "Serie A",
        "city": "Sao Paulo",
        "lat": -23.5489,
        "lon": -46.6388,
        "founded": 1930,
        "stadium": "Morumbi",
        "trophies": "Serie A: 6, Copa Libertadores: 3, Copa do Brasil: 1",
        "mustKnowFact": "Three-time world champs.",
        "active": true,
        "logo": "logos/sao_paulo.png",
        "uniform": "uniforms/sao_paulo.png"
    },
    {
        "name": "Fluminense",
        "country": "Brazil",
        "league": "Serie A",
        "city": "Rio de Janeiro",
        "lat": -22.911,
        "lon": -43.1729,
        "founded": 1902,
        "stadium": "Maracana",
        "trophies": "Serie A: 4, Copa Libertadores: 1, Copa do Brasil: 1",
        "mustKnowFact": "Tricolor elegance rules.",
        "active": true,
        "logo": "logos/fluminense.png",
        "uniform": "uniforms/fluminense.png"
    },
    {
        "name": "Gremio",
        "country": "Brazil",
        "league": "Serie A",
        "city": "Porto Alegre",
        "lat": -30.0346,
        "lon": -51.2177,
        "founded": 1903,
        "stadium": "Arena do Gremio",
        "trophies": "Serie A: 2, Copa Libertadores: 3, Copa do Brasil: 5",
        "mustKnowFact": "Imortal Tricolor fights on.",
        "active": true,
        "logo": "logos/gremio.png",
        "uniform": "uniforms/gremio.png"
    },
    {
        "name": "Internacional",
        "country": "Brazil",
        "league": "Serie A",
        "city": "Porto Alegre",
        "lat": -30.0655,
        "lon": -51.235,
        "founded": 1909,
        "stadium": "Beira-Rio",
        "trophies": "Serie A: 3, Copa Libertadores: 2, Copa do Brasil: 1",
        "mustKnowFact": "Colorado giants rise.",
        "active": true,
        "logo": "logos/internacional.png",
        "uniform": "uniforms/internacional.png"
    },
    {
        "name": "Atletico Mineiro",
        "country": "Brazil",
        "league": "Serie A",
        "city": "Belo Horizonte",
        "lat": -19.9173,
        "lon": -43.9345,
        "founded": 1908,
        "stadium": "Arena MRV",
        "trophies": "Serie A: 2, Copa Libertadores: 1, Copa do Brasil: 2",
        "mustKnowFact": "Galo\u00e2\u20ac\u2122s fierce roar.",
        "active": true,
        "logo": "logos/atletico_mineiro.png",
        "uniform": "uniforms/atletico_mineiro.png"
    },
    {
        "name": "Cruzeiro",
        "country": "Brazil",
        "league": "Serie A",
        "city": "Belo Horizonte",
        "lat": -19.9208,
        "lon": -43.9378,
        "founded": 1921,
        "stadium": "Mineirao",
        "trophies": "Serie A: 4, Copa Libertadores: 2, Copa do Brasil: 6",
        "mustKnowFact": "Raposa\u00e2\u20ac\u2122s trophy haul.",
        "active": true,
        "logo": "logos/cruzeiro.png",
        "uniform": "uniforms/cruzeiro.png"
    },
    {
        "name": "Botafogo",
        "country": "Brazil",
        "league": "Serie A",
        "city": "Rio de Janeiro",
        "lat": -22.9519,
        "lon": -43.175,
        "founded": 1904,
        "stadium": "Nilton Santos",
        "trophies": "Serie A: 2, Copa do Brasil: 1",
        "mustKnowFact": "Lone Star shines again.",
        "active": true,
        "logo": "logos/botafogo.png",
        "uniform": "uniforms/botafogo.png"
    },
    {
        "name": "Vasco da Gama",
        "country": "Brazil",
        "league": "Serie A",
        "city": "Rio de Janeiro",
        "lat": -22.8908,
        "lon": -43.228,
        "founded": 1898,
        "stadium": "Sao Januario",
        "trophies": "Serie A: 4, Copa Libertadores: 1, Copa do Brasil: 1",
        "mustKnowFact": "Cross of Malta legacy.",
        "active": true,
        "logo": "logos/vasco_da_gama.png",
        "uniform": "uniforms/vasco_da_gama.png"
    },
    {
        "name": "Bahia",
        "country": "Brazil",
        "league": "Serie A",
        "city": "Salvador",
        "lat": -12.9714,
        "lon": -38.5014,
        "founded": 1931,
        "stadium": "Arena Fonte Nova",
        "trophies": "Serie A: 2",
        "mustKnowFact": "Tricolor de A\u00c3\u00a7o\u00e2\u20ac\u2122s steel.",
        "active": true,
        "logo": "logos/bahia.png",
        "uniform": "uniforms/bahia.png"
    },
    {
        "name": "Athletico Paranaense",
        "country": "Brazil",
        "league": "Serie A",
        "city": "Curitiba",
        "lat": -25.4489,
        "lon": -49.3044,
        "founded": 1924,
        "stadium": "Arena da Baixada",
        "trophies": "Serie A: 1, Copa Sudamericana: 2, Copa do Brasil: 1",
        "mustKnowFact": "Furac\u00c3\u00a3o\u00e2\u20ac\u2122s storming force.",
        "active": true,
        "logo": "logos/athletico_paranaense.png",
        "uniform": "uniforms/athletico_paranaense.png"
    },
    {
        "name": "Fortaleza",
        "country": "Brazil",
        "league": "Serie A",
        "city": "Fortaleza",
        "lat": -3.7327,
        "lon": -38.527,
        "founded": 1918,
        "stadium": "Castelao",
        "trophies": "",
        "mustKnowFact": "Lion of the Northeast.",
        "active": true,
        "logo": "logos/fortaleza.png",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Bragantino",
        "country": "Brazil",
        "league": "Serie A",
        "city": "Braganca Paulista",
        "lat": -22.952,
        "lon": -46.5419,
        "founded": 1928,
        "stadium": "Nabi Abi Chedid",
        "trophies": "",
        "mustKnowFact": "Red Bull\u00e2\u20ac\u2122s Brazilian boost.",
        "active": true,
        "logo": "logos/bragantino.png",
        "uniform": "uniforms/bragantino.png"
    },
    {
        "name": "Cuiaba",
        "country": "Brazil",
        "league": "Serie A",
        "city": "Cuiaba",
        "lat": -15.5989,
        "lon": -56.0949,
        "founded": 2001,
        "stadium": "Arena Pantanal",
        "trophies": "",
        "mustKnowFact": "Golden Dourado rises.",
        "active": true,
        "logo": "logos/cuiaba.png",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Vitoria",
        "country": "Brazil",
        "league": "Serie A",
        "city": "Salvador",
        "lat": -12.9714,
        "lon": -38.5014,
        "founded": 1899,
        "stadium": "Barradao",
        "trophies": "",
        "mustKnowFact": "Red and black revival.",
        "active": true,
        "logo": "logos/vitoria.png",
        "uniform": "uniforms/vitoria.png"
    },
    {
        "name": "Atletico Goianiense",
        "country": "Brazil",
        "league": "Serie A",
        "city": "Goiania",
        "lat": -16.6869,
        "lon": -49.2648,
        "founded": 1937,
        "stadium": "Antonio Accioly",
        "trophies": "",
        "mustKnowFact": "Dragon\u00e2\u20ac\u2122s fiery ascent.",
        "active": true,
        "logo": "logos/atletico_goianiense.png",
        "uniform": "uniforms/atletico_goianiense.png"
    },
    {
        "name": "Juventude",
        "country": "Brazil",
        "league": "Serie A",
        "city": "Caxias do Sul",
        "lat": -29.1681,
        "lon": -51.1794,
        "founded": 1913,
        "stadium": "Alfredo Jaconi",
        "trophies": "Copa do Brasil: 1",
        "mustKnowFact": "Green resurgence in Serie A.",
        "active": true,
        "logo": "logos/juventude.png",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Juventus",
        "country": "Italy",
        "league": "Serie A",
        "city": "Turin",
        "lat": 45.0703,
        "lon": 7.6869,
        "founded": 1897,
        "stadium": "Allianz Stadium",
        "trophies": "Serie A: 36, Champions League: 2, Coppa Italia: 14",
        "mustKnowFact": "Italy\u00e2\u20ac\u2122s most successful club.",
        "active": true,
        "logo": "logos/juventus.png",
        "uniform": "uniforms/juventus.png"
    },
    {
        "name": "AC Milan",
        "country": "Italy",
        "league": "Serie A",
        "city": "Milan",
        "lat": 45.4642,
        "lon": 9.19,
        "founded": 1899,
        "stadium": "San Siro",
        "trophies": "Serie A: 19, Champions League: 7, Coppa Italia: 5",
        "mustKnowFact": "Seven-time European champs.",
        "active": true,
        "logo": "logos/ac_milan.png",
        "uniform": "uniforms/ac_milan.png"
    },
    {
        "name": "Inter Milan",
        "country": "Italy",
        "league": "Serie A",
        "city": "Milan",
        "lat": 45.4642,
        "lon": 9.19,
        "founded": 1908,
        "stadium": "San Siro",
        "trophies": "Serie A: 19, Champions League: 3, Coppa Italia: 8",
        "mustKnowFact": "The Nerazzurri\u00e2\u20ac\u2122s treble in 2010.",
        "active": true,
        "logo": "logos/inter_milan.png",
        "uniform": "uniforms/inter_milan.png"
    },
    {
        "name": "Napoli",
        "country": "Italy",
        "league": "Serie A",
        "city": "Naples",
        "lat": 40.8518,
        "lon": 14.2681,
        "founded": 1926,
        "stadium": "Stadio Diego Armando Maradona",
        "trophies": "Serie A: 3, Coppa Italia: 6, UEFA Cup: 1",
        "mustKnowFact": "Maradona\u00e2\u20ac\u2122s Naples legacy.",
        "active": true,
        "logo": "logos/napoli.png",
        "uniform": "uniforms/napoli.png"
    },
    {
        "name": "AS Roma",
        "country": "Italy",
        "league": "Serie A",
        "city": "Rome",
        "lat": 41.9028,
        "lon": 12.4964,
        "founded": 1927,
        "stadium": "Stadio Olimpico",
        "trophies": "Serie A: 3, Coppa Italia: 9, Conference League: 1",
        "mustKnowFact": "Totti\u00e2\u20ac\u2122s one-club legend.",
        "active": true,
        "logo": "https://via.placeholder.com/200?text=Logo",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Lazio",
        "country": "Italy",
        "league": "Serie A",
        "city": "Rome",
        "lat": 41.9028,
        "lon": 12.4964,
        "founded": 1900,
        "stadium": "Stadio Olimpico",
        "trophies": "Serie A: 2, Coppa Italia: 7, UEFA Cup Winners\u00e2\u20ac\u2122 Cup: 1",
        "mustKnowFact": "Eagles of Rome soar.",
        "active": true,
        "logo": "logos/lazio.png",
        "uniform": "uniforms/lazio.png"
    },
    {
        "name": "Fiorentina",
        "country": "Italy",
        "league": "Serie A",
        "city": "Florence",
        "lat": 43.7696,
        "lon": 11.2558,
        "founded": 1926,
        "stadium": "Stadio Artemio Franchi",
        "trophies": "Serie A: 2, Coppa Italia: 6",
        "mustKnowFact": "Viola\u00e2\u20ac\u2122s purple passion.",
        "active": true,
        "logo": "logos/fiorentina.png",
        "uniform": "uniforms/fiorentina.png"
    },
    {
        "name": "Atalanta",
        "country": "Italy",
        "league": "Serie A",
        "city": "Bergamo",
        "lat": 45.6983,
        "lon": 9.6773,
        "founded": 1907,
        "stadium": "Gewiss Stadium",
        "trophies": "Coppa Italia: 1",
        "mustKnowFact": "Underdog giant-killers.",
        "active": true,
        "logo": "logos/atalanta.png",
        "uniform": "uniforms/atalanta.png"
    },
    {
        "name": "Torino",
        "country": "Italy",
        "league": "Serie A",
        "city": "Turin",
        "lat": 45.0703,
        "lon": 7.6869,
        "founded": 1906,
        "stadium": "Stadio Olimpico Grande Torino",
        "trophies": "Serie A: 7, Coppa Italia: 5",
        "mustKnowFact": "Grande Torino\u00e2\u20ac\u2122s tragic legacy.",
        "active": true,
        "logo": "logos/torino.png",
        "uniform": "uniforms/torino.png"
    },
    {
        "name": "Bologna",
        "country": "Italy",
        "league": "Serie A",
        "city": "Bologna",
        "lat": 44.4949,
        "lon": 11.3426,
        "founded": 1909,
        "stadium": "Stadio Renato Dall\u00e2\u20ac\u2122Ara",
        "trophies": "Serie A: 7, Coppa Italia: 2",
        "mustKnowFact": "Historic Italian pioneers.",
        "active": true,
        "logo": "logos/bologna.png",
        "uniform": "uniforms/bologna.png"
    },
    {
        "name": "Udinese",
        "country": "Italy",
        "league": "Serie A",
        "city": "Udine",
        "lat": 46.0605,
        "lon": 13.243,
        "founded": 1896,
        "stadium": "Dacia Arena",
        "trophies": "",
        "mustKnowFact": "Friuli\u00e2\u20ac\u2122s black-and-white.",
        "active": true,
        "logo": "logos/udinese.png",
        "uniform": "uniforms/udinese.png"
    },
    {
        "name": "Sassuolo",
        "country": "Italy",
        "league": "Serie A",
        "city": "Sassuolo",
        "lat": 44.5442,
        "lon": 10.7848,
        "founded": 1920,
        "stadium": "Mapei Stadium",
        "trophies": "",
        "mustKnowFact": "Green-and-black overachievers.",
        "active": true,
        "logo": "logos/sassuolo.png",
        "uniform": "uniforms/sassuolo.png"
    },
    {
        "name": "Empoli",
        "country": "Italy",
        "league": "Serie A",
        "city": "Empoli",
        "lat": 43.7176,
        "lon": 10.9476,
        "founded": 1920,
        "stadium": "Stadio Carlo Castellani",
        "trophies": "",
        "mustKnowFact": "Tuscany\u00e2\u20ac\u2122s blue battlers.",
        "active": true,
        "logo": "logos/empoli.png",
        "uniform": "uniforms/empoli.png"
    },
    {
        "name": "Salernitana",
        "country": "Italy",
        "league": "Serie A",
        "city": "Salerno",
        "lat": 40.6824,
        "lon": 14.7681,
        "founded": 1919,
        "stadium": "Stadio Arechi",
        "trophies": "",
        "mustKnowFact": "Granata\u00e2\u20ac\u2122s southern spirit.",
        "active": true,
        "logo": "logos/salernitana.png",
        "uniform": "uniforms/salernitana.png"
    },
    {
        "name": "Monza",
        "country": "Italy",
        "league": "Serie A",
        "city": "Monza",
        "lat": 45.5845,
        "lon": 9.2749,
        "founded": 1912,
        "stadium": "U-Power Stadium",
        "trophies": "",
        "mustKnowFact": "Berlusconi\u00e2\u20ac\u2122s late project.",
        "active": true,
        "logo": "logos/monza.png",
        "uniform": "uniforms/monza.png"
    },
    {
        "name": "Genoa",
        "country": "Italy",
        "league": "Serie A",
        "city": "Genoa",
        "lat": 44.4056,
        "lon": 8.9463,
        "founded": 1893,
        "stadium": "Stadio Luigi Ferraris",
        "trophies": "Serie A: 9, Coppa Italia: 1",
        "mustKnowFact": "Italy\u00e2\u20ac\u2122s oldest club.",
        "active": true,
        "logo": "logos/genoa.png",
        "uniform": "uniforms/genoa.png"
    },
    {
        "name": "Cagliari",
        "country": "Italy",
        "league": "Serie A",
        "city": "Cagliari",
        "lat": 39.2238,
        "lon": 9.1217,
        "founded": 1920,
        "stadium": "Unipol Domus",
        "trophies": "Serie A: 1",
        "mustKnowFact": "Sardinia\u00e2\u20ac\u2122s lone champs.",
        "active": true,
        "logo": "logos/cagliari.png",
        "uniform": "uniforms/cagliari.png"
    },
    {
        "name": "Hellas Verona",
        "country": "Italy",
        "league": "Serie A",
        "city": "Verona",
        "lat": 45.4384,
        "lon": 10.9916,
        "founded": 1903,
        "stadium": "Stadio Marcantonio Bentegodi",
        "trophies": "Serie A: 1",
        "mustKnowFact": "1985\u00e2\u20ac\u2122s shock Scudetto.",
        "active": true,
        "logo": "https://via.placeholder.com/200?text=Logo",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Parma",
        "country": "Italy",
        "league": "Serie A",
        "city": "Parma",
        "lat": 44.8015,
        "lon": 10.328,
        "founded": 1913,
        "stadium": "Stadio Ennio Tardini",
        "trophies": "Coppa Italia: 3, UEFA Cup: 2",
        "mustKnowFact": "90s European glory.",
        "active": true,
        "logo": "https://via.placeholder.com/200?text=Logo",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Lecce",
        "country": "Italy",
        "league": "Serie A",
        "city": "Lecce",
        "lat": 40.3515,
        "lon": 18.158,
        "founded": 1908,
        "stadium": "Stadio Via del Mare",
        "trophies": "",
        "mustKnowFact": "Apulia\u00e2\u20ac\u2122s yellow-and-red.",
        "active": true,
        "logo": "logos/lecce.png",
        "uniform": "uniforms/lecce.png"
    },
    {
        "name": "Bayern Munich",
        "country": "Germany",
        "league": "Bundesliga",
        "city": "Munich",
        "lat": 48.1351,
        "lon": 11.582,
        "founded": 1900,
        "stadium": "Allianz Arena",
        "trophies": "Bundesliga: 32, Champions League: 6, DFB-Pokal: 20",
        "mustKnowFact": "Germany\u00e2\u20ac\u2122s dominant force.",
        "active": true,
        "logo": "logos/bayern_munich.png",
        "uniform": "uniforms/bayern_munich.png"
    },
    {
        "name": "Borussia Dortmund",
        "country": "Germany",
        "league": "Bundesliga",
        "city": "Dortmund",
        "lat": 51.5136,
        "lon": 7.4653,
        "founded": 1909,
        "stadium": "Signal Iduna Park",
        "trophies": "Bundesliga: 8, Champions League: 1, DFB-Pokal: 5",
        "mustKnowFact": "The Yellow Wall roars.",
        "active": true,
        "logo": "logos/borussia_dortmund.png",
        "uniform": "uniforms/borussia_dortmund.png"
    },
    {
        "name": "RB Leipzig",
        "country": "Germany",
        "league": "Bundesliga",
        "city": "Leipzig",
        "lat": 51.3397,
        "lon": 12.3731,
        "founded": 2009,
        "stadium": "Red Bull Arena",
        "trophies": "DFB-Pokal: 1",
        "mustKnowFact": "Red Bull\u00e2\u20ac\u2122s rapid rise.",
        "active": true,
        "logo": "logos/rb_leipzig.png",
        "uniform": "uniforms/rb_leipzig.png"
    },
    {
        "name": "Bayer Leverkusen",
        "country": "Germany",
        "league": "Bundesliga",
        "city": "Leverkusen",
        "lat": 51.038,
        "lon": 6.9845,
        "founded": 1904,
        "stadium": "BayArena",
        "trophies": "Bundesliga: 1, DFB-Pokal: 1, UEFA Cup: 1",
        "mustKnowFact": "Xabi Alonso\u00e2\u20ac\u2122s 2024 triumph.",
        "active": true,
        "logo": "logos/bayer_leverkusen.png",
        "uniform": "uniforms/bayer_leverkusen.png"
    },
    {
        "name": "Borussia Monchengladbach",
        "country": "Germany",
        "league": "Bundesliga",
        "city": "Monchengladbach",
        "lat": 51.1916,
        "lon": 6.442,
        "founded": 1900,
        "stadium": "Borussia-Park",
        "trophies": "Bundesliga: 5, UEFA Cup: 2, DFB-Pokal: 3",
        "mustKnowFact": "70s German dynasty.",
        "active": true,
        "logo": "logos/borussia_monchengladbach.png",
        "uniform": "uniforms/borussia_monchengladbach.png"
    },
    {
        "name": "VfB Stuttgart",
        "country": "Germany",
        "league": "Bundesliga",
        "city": "Stuttgart",
        "lat": 48.7758,
        "lon": 9.1829,
        "founded": 1893,
        "stadium": "Mercedes-Benz Arena",
        "trophies": "Bundesliga: 5, DFB-Pokal: 3",
        "mustKnowFact": "Swabian pride endures.",
        "active": true,
        "logo": "logos/vfb_stuttgart.png",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Eintracht Frankfurt",
        "country": "Germany",
        "league": "Bundesliga",
        "city": "Frankfurt",
        "lat": 50.1109,
        "lon": 8.6821,
        "founded": 1899,
        "stadium": "Deutsche Bank Park",
        "trophies": "Bundesliga: 1, Europa League: 2, DFB-Pokal: 5",
        "mustKnowFact": "2022 Europa kings.",
        "active": true,
        "logo": "logos/eintracht_frankfurt.png",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Wolfsburg",
        "country": "Germany",
        "league": "Bundesliga",
        "city": "Wolfsburg",
        "lat": 52.4245,
        "lon": 10.7867,
        "founded": 1945,
        "stadium": "Volkswagen Arena",
        "trophies": "Bundesliga: 1, DFB-Pokal: 1",
        "mustKnowFact": "VW\u00e2\u20ac\u2122s football venture.",
        "active": true,
        "logo": "logos/wolfsburg.png",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Freiburg",
        "country": "Germany",
        "league": "Bundesliga",
        "city": "Freiburg",
        "lat": 47.999,
        "lon": 7.8421,
        "founded": 1904,
        "stadium": "Europa-Park Stadion",
        "trophies": "",
        "mustKnowFact": "Black Forest overachievers.",
        "active": true,
        "logo": "logos/freiburg.png",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Mainz 05",
        "country": "Germany",
        "league": "Bundesliga",
        "city": "Mainz",
        "lat": 49.9929,
        "lon": 8.2473,
        "founded": 1905,
        "stadium": "Mewa Arena",
        "trophies": "",
        "mustKnowFact": "Carnival club\u00e2\u20ac\u2122s grit.",
        "active": true,
        "logo": "https://via.placeholder.com/200?text=Logo",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Hoffenheim",
        "country": "Germany",
        "league": "Bundesliga",
        "city": "Sinsheim",
        "lat": 49.2529,
        "lon": 8.887,
        "founded": 1899,
        "stadium": "PreZero Arena",
        "trophies": "",
        "mustKnowFact": "Village club\u00e2\u20ac\u2122s miracle.",
        "active": true,
        "logo": "logos/hoffenheim.png",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Augsburg",
        "country": "Germany",
        "league": "Bundesliga",
        "city": "Augsburg",
        "lat": 48.3705,
        "lon": 10.8978,
        "founded": 1907,
        "stadium": "WWK Arena",
        "trophies": "",
        "mustKnowFact": "Bavarian underdogs thrive.",
        "active": true,
        "logo": "logos/augsburg.png",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Werder Bremen",
        "country": "Germany",
        "league": "Bundesliga",
        "city": "Bremen",
        "lat": 53.0793,
        "lon": 8.8017,
        "founded": 1899,
        "stadium": "Weserstadion",
        "trophies": "Bundesliga: 4, DFB-Pokal: 6",
        "mustKnowFact": "Green-and-white tradition.",
        "active": true,
        "logo": "logos/werder_bremen.png",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Union Berlin",
        "country": "Germany",
        "league": "Bundesliga",
        "city": "Berlin",
        "lat": 52.52,
        "lon": 13.405,
        "founded": 1966,
        "stadium": "Stadion An der Alten Forsterei",
        "trophies": "",
        "mustKnowFact": "East Berlin\u00e2\u20ac\u2122s cult heroes.",
        "active": true,
        "logo": "logos/union_berlin.png",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Bochum",
        "country": "Germany",
        "league": "Bundesliga",
        "city": "Bochum",
        "lat": 51.4818,
        "lon": 7.2162,
        "founded": 1848,
        "stadium": "Vonovia Ruhrstadion",
        "trophies": "",
        "mustKnowFact": "Ruhr\u00e2\u20ac\u2122s blue-and-white.",
        "active": true,
        "logo": "logos/bochum.png",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Koln",
        "country": "Germany",
        "league": "Bundesliga",
        "city": "Cologne",
        "lat": 50.9375,
        "lon": 6.9603,
        "founded": 1948,
        "stadium": "RheinEnergieStadion",
        "trophies": "Bundesliga: 3, DFB-Pokal: 4",
        "mustKnowFact": "The Billy Goats\u00e2\u20ac\u2122 spirit.",
        "active": true,
        "logo": "https://via.placeholder.com/200?text=Logo",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Heidenheim",
        "country": "Germany",
        "league": "Bundesliga",
        "city": "Heidenheim",
        "lat": 48.676,
        "lon": 10.1545,
        "founded": 1846,
        "stadium": "Voith-Arena",
        "trophies": "",
        "mustKnowFact": "Tiny town\u00e2\u20ac\u2122s big dream.",
        "active": true,
        "logo": "https://via.placeholder.com/200?text=Logo",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Holstein Kiel",
        "country": "Germany",
        "league": "Bundesliga",
        "city": "Kiel",
        "lat": 54.3233,
        "lon": 10.1228,
        "founded": 1900,
        "stadium": "Holstein-Stadion",
        "trophies": "",
        "mustKnowFact": "Northern newcomers in 2024.",
        "active": true,
        "logo": "logos/holstein_kiel.png",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Schalke 04",
        "country": "Germany",
        "league": "Bundesliga",
        "city": "Gelsenkirchen",
        "lat": 51.555,
        "lon": 7.0665,
        "founded": 1904,
        "stadium": "Veltins-Arena",
        "trophies": "Bundesliga: 7, DFB-Pokal: 5, UEFA Cup: 1",
        "mustKnowFact": "Miners\u00e2\u20ac\u2122 blue legacy.",
        "active": true,
        "logo": "logos/schalke_04.png",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Hamburg SV",
        "country": "Germany",
        "league": "Bundesliga",
        "city": "Hamburg",
        "lat": 53.5488,
        "lon": 9.9937,
        "founded": 1887,
        "stadium": "Volksparkstadion",
        "trophies": "Bundesliga: 6, Champions League: 1, DFB-Pokal: 3",
        "mustKnowFact": "Northern giants aim back.",
        "active": true,
        "logo": "https://via.placeholder.com/200?text=Logo",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Benfica",
        "country": "Portugal",
        "league": "Primeira Liga",
        "city": "Lisbon",
        "lat": 38.7223,
        "lon": -9.1393,
        "founded": 1904,
        "stadium": "Estadio da Luz",
        "trophies": "Primeira Liga: 38, Champions League: 2, Taca de Portugal: 26",
        "mustKnowFact": "Eagles dominate Portugal.",
        "active": true,
        "logo": "logos/benfica.png",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Porto",
        "country": "Portugal",
        "league": "Primeira Liga",
        "city": "Porto",
        "lat": 41.1579,
        "lon": -8.6291,
        "founded": 1893,
        "stadium": "Estadio do Dragao",
        "trophies": "Primeira Liga: 30, Champions League: 2, Taca de Portugal: 19",
        "mustKnowFact": "Dragons\u00e2\u20ac\u2122 European glory.",
        "active": true,
        "logo": "logos/porto.png",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Sporting CP",
        "country": "Portugal",
        "league": "Primeira Liga",
        "city": "Lisbon",
        "lat": 38.7223,
        "lon": -9.1393,
        "founded": 1906,
        "stadium": "Estadio Jose Alvalade",
        "trophies": "Primeira Liga: 19, Taca de Portugal: 17",
        "mustKnowFact": "Lions roar in green.",
        "active": true,
        "logo": "logos/sporting_cp.png",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Braga",
        "country": "Portugal",
        "league": "Primeira Liga",
        "city": "Braga",
        "lat": 41.5454,
        "lon": -8.4265,
        "founded": 1921,
        "stadium": "Estadio Municipal de Braga",
        "trophies": "Taca de Portugal: 3",
        "mustKnowFact": "The Arsenalists challenge big three.",
        "active": true,
        "logo": "logos/braga.png",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Vitoria Guimaraes",
        "country": "Portugal",
        "league": "Primeira Liga",
        "city": "Guimaraes",
        "lat": 41.4425,
        "lon": -8.2938,
        "founded": 1922,
        "stadium": "Estadio D. Afonso Henriques",
        "trophies": "Taca de Portugal: 1",
        "mustKnowFact": "Conquerors of the north.",
        "active": true,
        "logo": "https://via.placeholder.com/200?text=Logo",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Boavista",
        "country": "Portugal",
        "league": "Primeira Liga",
        "city": "Porto",
        "lat": 41.1579,
        "lon": -8.6291,
        "founded": 1903,
        "stadium": "Estadio do Bessa",
        "trophies": "Primeira Liga: 1, Taca de Portugal: 5",
        "mustKnowFact": "Panthers\u00e2\u20ac\u2122 2001 surprise.",
        "active": true,
        "logo": "logos/boavista.png",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Famalic\u00c3\u00a3o",
        "country": "Portugal",
        "league": "Primeira Liga",
        "city": "Vila Nova de Famalic\u00c3\u00a3o",
        "lat": 41.4075,
        "lon": -8.5198,
        "founded": 1931,
        "stadium": "Estadio Municipal 22 de Junho",
        "trophies": "",
        "mustKnowFact": "Northern upstarts climb.",
        "active": true,
        "logo": "https://via.placeholder.com/200?text=Logo",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Gil Vicente",
        "country": "Portugal",
        "league": "Primeira Liga",
        "city": "Barcelos",
        "lat": 41.5317,
        "lon": -8.6189,
        "founded": 1924,
        "stadium": "Estadio Cidade de Barcelos",
        "trophies": "",
        "mustKnowFact": "Roosters crow in Barcelos.",
        "active": true,
        "logo": "logos/gil_vicente.png",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Moreirense",
        "country": "Portugal",
        "league": "Primeira Liga",
        "city": "Moreira de Conegos",
        "lat": 41.3858,
        "lon": -8.3398,
        "founded": 1938,
        "stadium": "Parque de Jogos Comendador Joaquim de Almeida Freitas",
        "trophies": "Taca da Liga: 1",
        "mustKnowFact": "Small town, big heart.",
        "active": true,
        "logo": "logos/moreirense.png",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Estoril",
        "country": "Portugal",
        "league": "Primeira Liga",
        "city": "Estoril",
        "lat": 38.7046,
        "lon": -9.3972,
        "founded": 1939,
        "stadium": "Estadio Antonio Coimbra da Mota",
        "trophies": "",
        "mustKnowFact": "Coastal yellow-and-blue.",
        "active": true,
        "logo": "https://via.placeholder.com/200?text=Logo",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Santa Clara",
        "country": "Portugal",
        "league": "Primeira Liga",
        "city": "Ponta Delgada",
        "lat": 37.7388,
        "lon": -25.668,
        "founded": 1927,
        "stadium": "Estadio de Sao Miguel",
        "trophies": "",
        "mustKnowFact": "Azores\u00e2\u20ac\u2122 lone warriors.",
        "active": true,
        "logo": "logos/santa_clara.png",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Rio Ave",
        "country": "Portugal",
        "league": "Primeira Liga",
        "city": "Vila do Conde",
        "lat": 41.3006,
        "lon": -8.7352,
        "founded": 1939,
        "stadium": "Estadio dos Arcos",
        "trophies": "",
        "mustKnowFact": "River Ave\u00e2\u20ac\u2122s green stripes.",
        "active": true,
        "logo": "logos/rio_ave.png",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Arouca",
        "country": "Portugal",
        "league": "Primeira Liga",
        "city": "Arouca",
        "lat": 40.9312,
        "lon": -8.2436,
        "founded": 1951,
        "stadium": "Estadio Municipal de Arouca",
        "trophies": "",
        "mustKnowFact": "Small-town yellow surprise.",
        "active": true,
        "logo": "logos/arouca.png",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Casa Pia",
        "country": "Portugal",
        "league": "Primeira Liga",
        "city": "Lisbon",
        "lat": 38.7223,
        "lon": -9.1393,
        "founded": 1920,
        "stadium": "Estadio Pina Manique",
        "trophies": "",
        "mustKnowFact": "Geese fly in Lisbon.",
        "active": true,
        "logo": "logos/casa_pia.png",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Farense",
        "country": "Portugal",
        "league": "Primeira Liga",
        "city": "Faro",
        "lat": 37.0194,
        "lon": -7.9307,
        "founded": 1910,
        "stadium": "Estadio de Sao Luis",
        "trophies": "",
        "mustKnowFact": "Algarve\u00e2\u20ac\u2122s lions roar.",
        "active": true,
        "logo": "https://via.placeholder.com/200?text=Logo",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Estrela da Amadora",
        "country": "Portugal",
        "league": "Primeira Liga",
        "city": "Amadora",
        "lat": 38.7596,
        "lon": -9.2245,
        "founded": 1932,
        "stadium": "Estadio Jose Gomes",
        "trophies": "Taca de Portugal: 1",
        "mustKnowFact": "Stars shine near Lisbon.",
        "active": true,
        "logo": "https://via.placeholder.com/200?text=Logo",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Nacional",
        "country": "Portugal",
        "league": "Primeira Liga",
        "city": "Funchal",
        "lat": 32.6702,
        "lon": -16.9241,
        "founded": 1910,
        "stadium": "Estadio da Madeira",
        "trophies": "",
        "mustKnowFact": "Madeira\u00e2\u20ac\u2122s black-and-white.",
        "active": true,
        "logo": "https://via.placeholder.com/200?text=Logo",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "AVS",
        "country": "Portugal",
        "league": "Primeira Liga",
        "city": "Vila das Aves",
        "lat": 41.3631,
        "lon": -8.4102,
        "founded": 1956,
        "stadium": "Estadio do CD Aves",
        "trophies": "",
        "mustKnowFact": "New kids from Aves.",
        "active": true,
        "logo": "https://via.placeholder.com/200?text=Logo",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Belenenses",
        "country": "Portugal",
        "league": "Primeira Liga",
        "city": "Lisbon",
        "lat": 38.7223,
        "lon": -9.1393,
        "founded": 1919,
        "stadium": "Estadio do Restelo",
        "trophies": "Primeira Liga: 1, Taca de Portugal: 3",
        "mustKnowFact": "Historic Lisbon blues.",
        "active": true,
        "logo": "https://via.placeholder.com/200?text=Logo",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Maritimo",
        "country": "Portugal",
        "league": "Primeira Liga",
        "city": "Funchal",
        "lat": 32.6702,
        "lon": -16.9241,
        "founded": 1910,
        "stadium": "Estadio do Maritimo",
        "trophies": "Taca de Portugal: 1",
        "mustKnowFact": "Madeira\u00e2\u20ac\u2122s green-and-red.",
        "active": true,
        "logo": "https://via.placeholder.com/200?text=Logo",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    }
];
