const teams = [
    {
        "name": "AC Milan",
        "country": "Italy",
        "league": "Serie A",
        "city": "Milan",
        "lat": 45.4642,
        "lon": 9.19,
        "founded": 1899,
        "stadium": "San Siro",
        "trophies": "Serie A: 19, Coppa Italia: 5, Supercoppa Italiana: 7, Champions League: 7, UEFA Super Cup: 5, Intercontinental Cup: 3",
        "mustKnowFact": "Seven-time European champs.",
        "active": true,
        "logo": "logos/ac_milan.png",
        "uniform": "uniforms/ac_milan.png"
    },
    {
        "name": "AJ Auxerre",
        "country": "France",
        "league": "Ligue 1",
        "city": "Auxerre",
        "lat": 47.7989,
        "lon": 3.5736,
        "founded": 1905,
        "stadium": "Stade de l'Abbé-Deschamps",
        "trophies": "Ligue 1: 1, Coupe de France: 4, Ligue 2: 2",
        "mustKnowFact": "Promoted back to Ligue 1 for 2024-25 after 2022 win.",
        "active": true,
        "logo": "https://via.placeholder.com/200?text=Logo",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "AS Monaco",
        "country": "France",
        "league": "Ligue 1",
        "city": "Monaco",
        "lat": 43.7333,
        "lon": 7.4167,
        "founded": 1924,
        "stadium": "Stade Louis II",
        "trophies": "Ligue 1: 8, Coupe de France: 5, Coupe de la Ligue: 1, Trophée des Champions: 4, Ligue 2: 3",
        "mustKnowFact": "Runner-up in Ligue 1 2023-24, facing PSG in 2024 Trophée.",
        "active": true,
        "logo": "logos/as_monaco.png",
        "uniform": "uniforms/as_monaco.png"
    },
    {
        "name": "AS Roma",
        "country": "Italy",
        "league": "Serie A",
        "city": "Rome",
        "lat": 41.9028,
        "lon": 12.4964,
        "founded": 1927,
        "stadium": "Stadio Olimpico",
        "trophies": "Serie A: 3, Coppa Italia: 9, Supercoppa Italiana: 2, Conference League: 1",
        "mustKnowFact": "Totti's one-club legend.",
        "active": true,
        "logo": "https://via.placeholder.com/200?text=Logo",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "AS Saint-Étienne",
        "country": "France",
        "league": "Ligue 1",
        "city": "Saint-Étienne",
        "lat": 45.4606,
        "lon": 4.3903,
        "founded": 1919,
        "stadium": "Stade Geoffroy-Guichard",
        "trophies": "Ligue 1: 10, Coupe de France: 6, Coupe de la Ligue: 1, Trophée des Champions: 5, Ligue 2: 3",
        "mustKnowFact": "Back in Ligue 1 for 2024-25 after two years.",
        "active": true,
        "logo": "https://via.placeholder.com/200?text=Logo",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "AVS",
        "country": "Portugal",
        "league": "Primeira Liga",
        "city": "Vila das Aves",
        "lat": 41.3631,
        "lon": -8.4102,
        "founded": 1956,
        "stadium": "Estadio do CD Aves",
        "trophies": "",
        "mustKnowFact": "New kids from Aves.",
        "active": true,
        "logo": "https://via.placeholder.com/200?text=Logo",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Alaves",
        "country": "Spain",
        "league": "La Liga",
        "city": "Vitoria-Gasteiz",
        "lat": 42.8506,
        "lon": -2.6724,
        "founded": 1921,
        "stadium": "Mendizorrotza",
        "trophies": "Segunda División: 4",
        "mustKnowFact": "Basque underdogs punch above.",
        "active": true,
        "logo": "logos/alaves.png",
        "uniform": "uniforms/alaves.png"
    },
    {
        "name": "Angers SCO",
        "country": "France",
        "league": "Ligue 1",
        "city": "Angers",
        "lat": 47.4656,
        "lon": -0.5558,
        "founded": 1919,
        "stadium": "Stade Raymond Kopa",
        "trophies": "Ligue 2: 2",
        "mustKnowFact": "Promoted to Ligue 1 for 2024-25.",
        "active": true,
        "logo": "logos/angers_sco.png",
        "uniform": "uniforms/angers_sco.png"
    },
    {
        "name": "Argentinos Juniors",
        "country": "Argentina",
        "league": "Primera División",
        "city": "Buenos Aires",
        "lat": -34.6076,
        "lon": -58.4472,
        "founded": 1904,
        "stadium": "Estadio Diego Armando Maradona",
        "trophies": "Primera División: 3, Copa Libertadores: 1, Copa Interamericana: 1",
        "mustKnowFact": "Maradona's launchpad.",
        "active": true,
        "logo": "logos/argentinos_juniors.png",
        "uniform": "uniforms/argentinos_juniors.png"
    },
    {
        "name": "Arouca",
        "country": "Portugal",
        "league": "Primeira Liga",
        "city": "Arouca",
        "lat": 40.9312,
        "lon": -8.2436,
        "founded": 1951,
        "stadium": "Estadio Municipal de Arouca",
        "trophies": "",
        "mustKnowFact": "Small-town yellow surprise.",
        "active": true,
        "logo": "logos/arouca.png",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Arsenal",
        "country": "England",
        "league": "Premier League",
        "city": "London",
        "lat": 51.5549,
        "lon": -0.1084,
        "founded": 1886,
        "stadium": "Emirates Stadium",
        "trophies": "Premier League: 3, First Division: 10, FA Cup: 14, League Cup: 2, Community Shield: 17, European Cup Winners' Cup: 1",
        "mustKnowFact": "The Invincibles of 2003-04.",
        "active": true,
        "logo": "logos/arsenal.png",
        "uniform": "uniforms/arsenal.png"
    },
    {
        "name": "Aston Villa",
        "country": "England",
        "league": "Premier League",
        "city": "Birmingham",
        "lat": 52.5091,
        "lon": -1.8848,
        "founded": 1874,
        "stadium": "Villa Park",
        "trophies": "First Division: 7, FA Cup: 7, League Cup: 5, Community Shield: 1, European Cup: 1, UEFA Super Cup: 1",
        "mustKnowFact": "1982 European champs.",
        "active": true,
        "logo": "logos/aston_villa.png",
        "uniform": "uniforms/aston_villa.png"
    },
    {
        "name": "Atalanta",
        "country": "Italy",
        "league": "Serie A",
        "city": "Bergamo",
        "lat": 45.6983,
        "lon": 9.6773,
        "founded": 1907,
        "stadium": "Gewiss Stadium",
        "trophies": "Serie B: 6, Coppa Italia: 1",
        "mustKnowFact": "Underdog giant-killers.",
        "active": true,
        "logo": "logos/atalanta.png",
        "uniform": "uniforms/atalanta.png"
    },
    {
        "name": "Athletic Bilbao",
        "country": "Spain",
        "league": "La Liga",
        "city": "Bilbao",
        "lat": 43.263,
        "lon": -2.934,
        "founded": 1898,
        "stadium": "San Mames",
        "trophies": "La Liga: 8, Copa del Rey: 23, Supercopa de España: 3",
        "mustKnowFact": "Only signs Basque players.",
        "active": true,
        "logo": "logos/athletic_bilbao.png",
        "uniform": "uniforms/athletic_bilbao.png"
    },
    {
        "name": "Athletico Paranaense",
        "country": "Brazil",
        "league": "Serie A",
        "city": "Curitiba",
        "lat": -25.4489,
        "lon": -49.3044,
        "founded": 1924,
        "stadium": "Arena da Baixada",
        "trophies": "Série A: 1, Copa do Brasil: 1, Copa Sudamericana: 2, Campeonato Paranaense: 27",
        "mustKnowFact": "FuracÃ£o's storming force.",
        "active": true,
        "logo": "logos/athletico_paranaense.png",
        "uniform": "uniforms/athletico_paranaense.png"
    },
    {
        "name": "Atletico Goianiense",
        "country": "Brazil",
        "league": "Serie A",
        "city": "Goiania",
        "lat": -16.6869,
        "lon": -49.2648,
        "founded": 1937,
        "stadium": "Antonio Accioly",
        "trophies": "Série B: 2, Campeonato Goiano: 15",
        "mustKnowFact": "Dragon's fiery ascent.",
        "active": true,
        "logo": "logos/atletico_goianiense.png",
        "uniform": "uniforms/atletico_goianiense.png"
    },
    {
        "name": "Atletico Madrid",
        "country": "Spain",
        "league": "La Liga",
        "city": "Madrid",
        "lat": 40.436,
        "lon": -3.5996,
        "founded": 1903,
        "stadium": "Wanda Metropolitano",
        "trophies": "La Liga: 11, Copa del Rey: 10, Supercopa de España: 2, Europa League: 3, UEFA Cup Winners' Cup: 1, UEFA Super Cup: 3",
        "mustKnowFact": "Simeone turned them into giants.",
        "active": true,
        "logo": "logos/atletico_madrid.png",
        "uniform": "uniforms/atletico_madrid.png"
    },
    {
        "name": "Atletico Mineiro",
        "country": "Brazil",
        "league": "Serie A",
        "city": "Belo Horizonte",
        "lat": -19.9173,
        "lon": -43.9345,
        "founded": 1908,
        "stadium": "Arena MRV",
        "trophies": "Série A: 2, Copa do Brasil: 2, Copa Libertadores: 1, Recopa Sudamericana: 1, Campeonato Mineiro: 48",
        "mustKnowFact": "Galo's fierce roar.",
        "active": true,
        "logo": "logos/atletico_mineiro.png",
        "uniform": "uniforms/atletico_mineiro.png"
    },
    {
        "name": "Atlético Tucumán",
        "country": "Argentina",
        "league": "Primera División",
        "city": "San Miguel de Tucumán",
        "lat": -26.8083,
        "lon": -65.2176,
        "founded": 1902,
        "stadium": "Estadio Monumental José Fierro",
        "trophies": "Primera B Nacional: 2",
        "mustKnowFact": "Tucumán's northern giants.",
        "active": true,
        "logo": "logos/atletico_tucuman.png",
        "uniform": "uniforms/atletico_tucuman.png"
    },
    {
        "name": "Augsburg",
        "country": "Germany",
        "league": "Bundesliga",
        "city": "Augsburg",
        "lat": 48.3705,
        "lon": 10.8978,
        "founded": 1907,
        "stadium": "WWK Arena",
        "trophies": "",
        "mustKnowFact": "Bavarian underdogs thrive.",
        "active": true,
        "logo": "logos/augsburg.png",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Bahia",
        "country": "Brazil",
        "league": "Serie A",
        "city": "Salvador",
        "lat": -12.9714,
        "lon": -38.5014,
        "founded": 1931,
        "stadium": "Arena Fonte Nova",
        "trophies": "Série A: 2, Copa do Nordeste: 4, Campeonato Baiano: 50",
        "mustKnowFact": "Tricolor de AÃ§o's steel.",
        "active": true,
        "logo": "logos/bahia.png",
        "uniform": "uniforms/bahia.png"
    },
    {
        "name": "Banfield",
        "country": "Argentina",
        "league": "Primera División",
        "city": "Banfield",
        "lat": -34.749,
        "lon": -58.3879,
        "founded": 1896,
        "stadium": "Estadio Florencio Sola",
        "trophies": "Primera División: 1, Primera B Nacional: 3",
        "mustKnowFact": "The Drill's southern grit.",
        "active": true,
        "logo": "logos/banfield.png",
        "uniform": "uniforms/banfield.png"
    },
    {
        "name": "Barcelona",
        "country": "Spain",
        "league": "La Liga",
        "city": "Barcelona",
        "lat": 41.3851,
        "lon": 2.1734,
        "founded": 1899,
        "stadium": "Camp Nou",
        "trophies": "La Liga: 27, Copa del Rey: 31, Supercopa de España: 14, Champions League: 5, UEFA Cup Winners' Cup: 4, UEFA Super Cup: 5, Club World Cup: 3",
        "mustKnowFact": "Messi's legendary career began here.",
        "active": true,
        "logo": "logos/barcelona.png",
        "uniform": "uniforms/barcelona.png"
    },
    {
        "name": "Barracas Central",
        "country": "Argentina",
        "league": "Primera División",
        "city": "Buenos Aires",
        "lat": -34.6417,
        "lon": -58.3881,
        "founded": 1904,
        "stadium": "Estadio Claudio Chiqui Tapia",
        "trophies": "Primera B Metropolitana: 1",
        "mustKnowFact": "Buenos Aires barrio climbers.",
        "active": true,
        "logo": "logos/barracas_central.png",
        "uniform": "uniforms/barracas_central.png"
    },
    {
        "name": "Bayer Leverkusen",
        "country": "Germany",
        "league": "Bundesliga",
        "city": "Leverkusen",
        "lat": 51.038,
        "lon": 6.9845,
        "founded": 1904,
        "stadium": "BayArena",
        "trophies": "Bundesliga: 1, DFB-Pokal: 2, UEFA Cup: 1",
        "mustKnowFact": "Xabi Alonso's 2024 triumph.",
        "active": true,
        "logo": "logos/bayer_leverkusen.png",
        "uniform": "uniforms/bayer_leverkusen.png"
    },
    {
        "name": "Bayern Munich",
        "country": "Germany",
        "league": "Bundesliga",
        "city": "Munich",
        "lat": 48.1351,
        "lon": 11.582,
        "founded": 1900,
        "stadium": "Allianz Arena",
        "trophies": "Bundesliga: 33, DFB-Pokal: 20, DFL-Supercup: 10, Champions League: 6, UEFA Cup: 1, UEFA Cup Winners' Cup: 1, Intercontinental Cup: 2, Club World Cup: 2",
        "mustKnowFact": "Germany's dominant force.",
        "active": true,
        "logo": "logos/bayern_munich.png",
        "uniform": "uniforms/bayern_munich.png"
    },
    {
        "name": "Belenenses",
        "country": "Portugal",
        "league": "Primeira Liga",
        "city": "Lisbon",
        "lat": 38.7223,
        "lon": -9.1393,
        "founded": 1919,
        "stadium": "Estadio do Restelo",
        "trophies": "Primeira Liga: 1, Taça de Portugal: 3",
        "mustKnowFact": "Historic Lisbon blues.",
        "active": true,
        "logo": "https://via.placeholder.com/200?text=Logo",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Belgrano",
        "country": "Argentina",
        "league": "Primera División",
        "city": "Córdoba",
        "lat": -31.4167,
        "lon": -64.1833,
        "founded": 1905,
        "stadium": "Estadio Julio César Villagra",
        "trophies": "Primera B Nacional: 2",
        "mustKnowFact": "Córdoba's pirate crew.",
        "active": true,
        "logo": "logos/belgrano.png",
        "uniform": "uniforms/belgrano.png"
    },
    {
        "name": "Benfica",
        "country": "Portugal",
        "league": "Primeira Liga",
        "city": "Lisbon",
        "lat": 38.7223,
        "lon": -9.1393,
        "founded": 1904,
        "stadium": "Estadio da Luz",
        "trophies": "Primeira Liga: 38, Taça de Portugal: 26, Taça da Liga: 7, Supertaça Cândido de Oliveira: 8, European Cup: 2",
        "mustKnowFact": "Eagles dominate Portugal.",
        "active": true,
        "logo": "logos/benfica.png",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Boavista",
        "country": "Portugal",
        "league": "Primeira Liga",
        "city": "Porto",
        "lat": 41.1579,
        "lon": -8.6291,
        "founded": 1903,
        "stadium": "Estadio do Bessa",
        "trophies": "Primeira Liga: 1, Taça de Portugal: 5, Supertaça Cândido de Oliveira: 3",
        "mustKnowFact": "Panthers' 2001 surprise.",
        "active": true,
        "logo": "logos/boavista.png",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Boca Juniors",
        "country": "Argentina",
        "league": "Primera División",
        "city": "Buenos Aires",
        "lat": -34.6355,
        "lon": -58.3648,
        "founded": 1905,
        "stadium": "La Bombonera",
        "trophies": "Primera División: 35, Copa Libertadores: 6, Intercontinental Cup: 3, Copa Sudamericana: 2, Recopa Sudamericana: 4, Copa Argentina: 4, Supercopa Argentina: 2",
        "mustKnowFact": "La Bombonera shakes with passion.",
        "active": true,
        "logo": "logos/boca_juniors.png",
        "uniform": "uniforms/boca_juniors.png"
    },
    {
        "name": "Bochum",
        "country": "Germany",
        "league": "Bundesliga",
        "city": "Bochum",
        "lat": 51.4818,
        "lon": 7.2162,
        "founded": 1848,
        "stadium": "Vonovia Ruhrstadion",
        "trophies": "2. Bundesliga: 4",
        "mustKnowFact": "Ruhr's blue-and-white.",
        "active": true,
        "logo": "logos/bochum.png",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Bologna",
        "country": "Italy",
        "league": "Serie A",
        "city": "Bologna",
        "lat": 44.4949,
        "lon": 11.3426,
        "founded": 1909,
        "stadium": "Stadio Renato Dall'Ara",
        "trophies": "Serie A: 7, Coppa Italia: 2",
        "mustKnowFact": "Historic Italian pioneers.",
        "active": true,
        "logo": "logos/bologna.png",
        "uniform": "uniforms/bologna.png"
    },
    {
        "name": "Borussia Dortmund",
        "country": "Germany",
        "league": "Bundesliga",
        "city": "Dortmund",
        "lat": 51.5136,
        "lon": 7.4653,
        "founded": 1909,
        "stadium": "Signal Iduna Park",
        "trophies": "Bundesliga: 8, DFB-Pokal: 5, DFL-Supercup: 6, Champions League: 1, UEFA Cup Winners' Cup: 1, Intercontinental Cup: 1",
        "mustKnowFact": "The Yellow Wall roars.",
        "active": true,
        "logo": "logos/borussia_dortmund.png",
        "uniform": "uniforms/borussia_dortmund.png"
    },
    {
        "name": "Borussia Monchengladbach",
        "country": "Germany",
        "league": "Bundesliga",
        "city": "Monchengladbach",
        "lat": 51.1916,
        "lon": 6.442,
        "founded": 1900,
        "stadium": "Borussia-Park",
        "trophies": "Bundesliga: 5, DFB-Pokal: 3, UEFA Cup: 2",
        "mustKnowFact": "70s German dynasty.",
        "active": true,
        "logo": "logos/borussia_monchengladbach.png",
        "uniform": "uniforms/borussia_monchengladbach.png"
    },
    {
        "name": "Botafogo",
        "country": "Brazil",
        "league": "Serie A",
        "city": "Rio de Janeiro",
        "lat": -22.9519,
        "lon": -43.175,
        "founded": 1904,
        "stadium": "Nilton Santos",
        "trophies": "Série A: 2, Campeonato Carioca: 21, Série B: 2",
        "mustKnowFact": "Lone Star shines again.",
        "active": true,
        "logo": "logos/botafogo.png",
        "uniform": "uniforms/botafogo.png"
    },
    {
        "name": "Bournemouth",
        "country": "England",
        "league": "Premier League",
        "city": "Bournemouth",
        "lat": 50.7352,
        "lon": -1.838,
        "founded": 1899,
        "stadium": "Vitality Stadium",
        "trophies": "Championship: 1, League One: 1",
        "mustKnowFact": "Cherries' coastal comeback.",
        "active": true,
        "logo": "logos/bournemouth.png",
        "uniform": "uniforms/bournemouth.png"
    },
    {
        "name": "Braga",
        "country": "Portugal",
        "league": "Primeira Liga",
        "city": "Braga",
        "lat": 41.5454,
        "lon": -8.4265,
        "founded": 1921,
        "stadium": "Estadio Municipal de Braga",
        "trophies": "Primeira Liga: 0, Taça de Portugal: 3, Taça da Liga: 2, Supertaça Cândido de Oliveira: 1",
        "mustKnowFact": "The Arsenalists challenge big three.",
        "active": true,
        "logo": "logos/braga.png",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Bragantino",
        "country": "Brazil",
        "league": "Serie A",
        "city": "Braganca Paulista",
        "lat": -22.952,
        "lon": -46.5419,
        "founded": 1928,
        "stadium": "Nabi Abi Chedid",
        "trophies": "Série B: 2, Campeonato Paulista: 1",
        "mustKnowFact": "Red Bull's Brazilian boost.",
        "active": true,
        "logo": "logos/bragantino.png",
        "uniform": "uniforms/bragantino.png"
    },
    {
        "name": "Brentford",
        "country": "England",
        "league": "Premier League",
        "city": "London",
        "lat": 51.4882,
        "lon": -0.3048,
        "founded": 1889,
        "stadium": "Gtech Community Stadium",
        "trophies": "Second Division/Championship: 1, Third Division: 2, Fourth Division: 1",
        "mustKnowFact": "Bees buzz in the top flight.",
        "active": true,
        "logo": "logos/brentford.png",
        "uniform": "uniforms/brentford.png"
    },
    {
        "name": "Brighton & Hove Albion",
        "country": "England",
        "league": "Premier League",
        "city": "Brighton",
        "lat": 50.8294,
        "lon": -0.1391,
        "founded": 1901,
        "stadium": "Amex Stadium",
        "trophies": "Third Division/League One: 3, Second Division/Championship: 2",
        "mustKnowFact": "Seagulls soaring in style.",
        "active": true,
        "logo": "https://via.placeholder.com/200?text=Logo",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Cagliari",
        "country": "Italy",
        "league": "Serie A",
        "city": "Cagliari",
        "lat": 39.2238,
        "lon": 9.1217,
        "founded": 1920,
        "stadium": "Unipol Domus",
        "trophies": "Serie A: 1, Serie B: 3",
        "mustKnowFact": "Sardinia's lone champs.",
        "active": true,
        "logo": "logos/cagliari.png",
        "uniform": "uniforms/cagliari.png"
    },
    {
        "name": "Casa Pia",
        "country": "Portugal",
        "league": "Primeira Liga",
        "city": "Lisbon",
        "lat": 38.7223,
        "lon": -9.1393,
        "founded": 1920,
        "stadium": "Estadio Pina Manique",
        "trophies": "",
        "mustKnowFact": "Geese fly in Lisbon.",
        "active": true,
        "logo": "logos/casa_pia.png",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Celta Vigo",
        "country": "Spain",
        "league": "La Liga",
        "city": "Vigo",
        "lat": 42.2406,
        "lon": -8.7207,
        "founded": 1923,
        "stadium": "Balaidos",
        "trophies": "Segunda División: 3",
        "mustKnowFact": "Galician tenacity shines.",
        "active": true,
        "logo": "logos/celta_vigo.png",
        "uniform": "uniforms/celta_vigo.png"
    },
    {
        "name": "Central Córdoba SdE",
        "country": "Argentina",
        "league": "Primera División",
        "city": "Santiago del Estero",
        "lat": -27.7833,
        "lon": -64.2667,
        "founded": 1919,
        "stadium": "Estadio Alfredo Terrera",
        "trophies": "Primera B Nacional: 1",
        "mustKnowFact": "Railway roots in Santiago.",
        "active": true,
        "logo": "https://via.placeholder.com/200?text=Logo",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Chelsea",
        "country": "England",
        "league": "Premier League",
        "city": "London",
        "lat": 51.4816,
        "lon": -0.191,
        "founded": 1905,
        "stadium": "Stamford Bridge",
        "trophies": "Premier League: 6, First Division: 1, FA Cup: 8, League Cup: 5, Community Shield: 4, Champions League: 2, Europa League: 2, UEFA Cup Winners' Cup: 2, UEFA Super Cup: 2",
        "mustKnowFact": "Abramovich's trophy era.",
        "active": true,
        "logo": "logos/chelsea.png",
        "uniform": "uniforms/chelsea.png"
    },
    {
        "name": "Corinthians",
        "country": "Brazil",
        "league": "Serie A",
        "city": "Sao Paulo",
        "lat": -23.5453,
        "lon": -46.4731,
        "founded": 1910,
        "stadium": "Neo Quimica Arena",
        "trophies": "Série A: 7, Copa do Brasil: 3, Campeonato Paulista: 30, Copa Libertadores: 1, Club World Cup: 2",
        "mustKnowFact": "TimÃ£o's loyal army.",
        "active": true,
        "logo": "logos/corinthians.png",
        "uniform": "uniforms/corinthians.png"
    },
    {
        "name": "Cruzeiro",
        "country": "Brazil",
        "league": "Serie A",
        "city": "Belo Horizonte",
        "lat": -19.9208,
        "lon": -43.9378,
        "founded": 1921,
        "stadium": "Mineirao",
        "trophies": "Série A: 4, Copa do Brasil: 6, Campeonato Mineiro: 38, Copa Libertadores: 2",
        "mustKnowFact": "Raposa's trophy haul.",
        "active": true,
        "logo": "logos/cruzeiro.png",
        "uniform": "uniforms/cruzeiro.png"
    },
    {
        "name": "Crystal Palace",
        "country": "England",
        "league": "Premier League",
        "city": "London",
        "lat": 51.3983,
        "lon": -0.0855,
        "founded": 1905,
        "stadium": "Selhurst Park",
        "trophies": "Championship: 2",
        "mustKnowFact": "Eagles of Selhurst soar.",
        "active": true,
        "logo": "logos/crystal_palace.png",
        "uniform": "uniforms/crystal_palace.png"
    },
    {
        "name": "Cuiaba",
        "country": "Brazil",
        "league": "Serie A",
        "city": "Cuiaba",
        "lat": -15.5989,
        "lon": -56.0949,
        "founded": 2001,
        "stadium": "Arena Pantanal",
        "trophies": "Campeonato Mato-Grossense: 11",
        "mustKnowFact": "Golden Dourado rises.",
        "active": true,
        "logo": "logos/cuiaba.png",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Defensa y Justicia",
        "country": "Argentina",
        "league": "Primera División",
        "city": "Florencio Varela",
        "lat": -34.8167,
        "lon": -58.2833,
        "founded": 1935,
        "stadium": "Estadio Norberto Tito Tomaghello",
        "trophies": "Copa Sudamericana: 1, Recopa Sudamericana: 1, Primera B Nacional: 1",
        "mustKnowFact": "Small club, massive 2020 Copa win.",
        "active": true,
        "logo": "logos/defensa_y_justicia.png",
        "uniform": "uniforms/defensa_y_justicia.png"
    },
    {
        "name": "Deportivo Riestra",
        "country": "Argentina",
        "league": "Primera División",
        "city": "Buenos Aires",
        "lat": -34.6667,
        "lon": -58.4667,
        "founded": 1931,
        "stadium": "Estadio Guillermo Laza",
        "trophies": "Primera B Metropolitana: 1",
        "mustKnowFact": "Primera debutants in 2024.",
        "active": true,
        "logo": "logos/deportivo_riestra.png",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Eintracht Frankfurt",
        "country": "Germany",
        "league": "Bundesliga",
        "city": "Frankfurt",
        "lat": 50.1109,
        "lon": 8.6821,
        "founded": 1899,
        "stadium": "Deutsche Bank Park",
        "trophies": "Bundesliga: 1, DFB-Pokal: 5, UEFA Cup/Europa League: 2",
        "mustKnowFact": "2022 Europa kings.",
        "active": true,
        "logo": "logos/eintracht_frankfurt.png",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Empoli",
        "country": "Italy",
        "league": "Serie A",
        "city": "Empoli",
        "lat": 43.7176,
        "lon": 10.9476,
        "founded": 1920,
        "stadium": "Stadio Carlo Castellani",
        "trophies": "Serie B: 3",
        "mustKnowFact": "Tuscany's blue battlers.",
        "active": true,
        "logo": "logos/empoli.png",
        "uniform": "uniforms/empoli.png"
    },
    {
        "name": "Espanyol",
        "country": "Spain",
        "league": "La Liga",
        "city": "Barcelona",
        "lat": 41.3478,
        "lon": 2.0757,
        "founded": 1900,
        "stadium": "RCDE Stadium",
        "trophies": "Copa del Rey: 4, Segunda División: 2",
        "mustKnowFact": "Barcelona's quieter rival.",
        "active": true,
        "logo": "logos/espanyol.png",
        "uniform": "uniforms/espanyol.png"
    },
    {
        "name": "Estoril",
        "country": "Portugal",
        "league": "Primeira Liga",
        "city": "Estoril",
        "lat": 38.7046,
        "lon": -9.3972,
        "founded": 1939,
        "stadium": "Estadio Antonio Coimbra da Mota",
        "trophies": "",
        "mustKnowFact": "Coastal yellow-and-blue.",
        "active": true,
        "logo": "https://via.placeholder.com/200?text=Logo",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Estrela da Amadora",
        "country": "Portugal",
        "league": "Primeira Liga",
        "city": "Amadora",
        "lat": 38.7596,
        "lon": -9.2245,
        "founded": 1932,
        "stadium": "Estadio Jose Gomes",
        "trophies": "Taça de Portugal: 1",
        "mustKnowFact": "Stars shine near Lisbon.",
        "active": true,
        "logo": "https://via.placeholder.com/200?text=Logo",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Estudiantes de La Plata",
        "country": "Argentina",
        "league": "Primera División",
        "city": "La Plata",
        "lat": -34.9137,
        "lon": -57.9391,
        "founded": 1905,
        "stadium": "Estadio Jorge Luis Hirschi",
        "trophies": "Primera División: 6, Copa Libertadores: 4, Intercontinental Cup: 1, Copa Argentina: 1",
        "mustKnowFact": "1960s global conquerors.",
        "active": true,
        "logo": "logos/estudiantes_de_la_plata.png",
        "uniform": "uniforms/estudiantes_de_la_plata.png"
    },
    {
        "name": "Everton",
        "country": "England",
        "league": "Premier League",
        "city": "Liverpool",
        "lat": 53.4388,
        "lon": -2.9663,
        "founded": 1878,
        "stadium": "Goodison Park",
        "trophies": "First Division: 9, FA Cup: 5, Community Shield: 9, European Cup Winners' Cup: 1",
        "mustKnowFact": "Toffees' historic Goodison.",
        "active": true,
        "logo": "logos/everton.png",
        "uniform": "uniforms/everton.png"
    },
    {
        "name": "FC Nantes",
        "country": "France",
        "league": "Ligue 1",
        "city": "Nantes",
        "lat": 47.2558,
        "lon": -1.5247,
        "founded": 1943,
        "stadium": "Stade de la Beaujoire",
        "trophies": "Ligue 1: 8, Coupe de France: 4, Coupe de la Ligue: 1, Trophée des Champions: 3",
        "mustKnowFact": "Historic giants clinging to Ligue 1.",
        "active": true,
        "logo": "logos/fc_nantes.png",
        "uniform": "uniforms/fc_nantes.png"
    },
    {
        "name": "FamalicÃ£o",
        "country": "Portugal",
        "league": "Primeira Liga",
        "city": "Vila Nova de FamalicÃ£o",
        "lat": 41.4075,
        "lon": -8.5198,
        "founded": 1931,
        "stadium": "Estadio Municipal 22 de Junho",
        "trophies": "",
        "mustKnowFact": "Northern upstarts climb.",
        "active": true,
        "logo": "https://via.placeholder.com/200?text=Logo",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Farense",
        "country": "Portugal",
        "league": "Primeira Liga",
        "city": "Faro",
        "lat": 37.0194,
        "lon": -7.9307,
        "founded": 1910,
        "stadium": "Estadio de Sao Luis",
        "trophies": "",
        "mustKnowFact": "Algarve's lions roar.",
        "active": true,
        "logo": "https://via.placeholder.com/200?text=Logo",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Fiorentina",
        "country": "Italy",
        "league": "Serie A",
        "city": "Florence",
        "lat": 43.7696,
        "lon": 11.2558,
        "founded": 1926,
        "stadium": "Stadio Artemio Franchi",
        "trophies": "Serie A: 2, Coppa Italia: 6, UEFA Cup Winners' Cup: 1, Serie B: 3",
        "mustKnowFact": "Viola's purple passion.",
        "active": true,
        "logo": "logos/fiorentina.png",
        "uniform": "uniforms/fiorentina.png"
    },
    {
        "name": "Flamengo",
        "country": "Brazil",
        "league": "Serie A",
        "city": "Rio de Janeiro",
        "lat": -22.9083,
        "lon": -43.1964,
        "founded": 1895,
        "stadium": "Maracana",
        "trophies": "Série A: 7, Copa do Brasil: 4, Campeonato Carioca: 37, Copa Libertadores: 3, Intercontinental Cup: 1",
        "mustKnowFact": "Brazil's most popular club.",
        "active": true,
        "logo": "logos/flamengo.png",
        "uniform": "uniforms/flamengo.png"
    },
    {
        "name": "Fluminense",
        "country": "Brazil",
        "league": "Serie A",
        "city": "Rio de Janeiro",
        "lat": -22.911,
        "lon": -43.1729,
        "founded": 1902,
        "stadium": "Maracana",
        "trophies": "Série A: 4, Copa do Brasil: 1, Campeonato Carioca: 33, Copa Libertadores: 1",
        "mustKnowFact": "Tricolor elegance rules.",
        "active": true,
        "logo": "logos/fluminense.png",
        "uniform": "uniforms/fluminense.png"
    },
    {
        "name": "Fortaleza",
        "country": "Brazil",
        "league": "Serie A",
        "city": "Fortaleza",
        "lat": -3.7327,
        "lon": -38.527,
        "founded": 1918,
        "stadium": "Castelao",
        "trophies": "Série B: 1, Copa do Nordeste: 3, Campeonato Cearense: 46",
        "mustKnowFact": "Lion of the Northeast.",
        "active": true,
        "logo": "logos/fortaleza.png",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Freiburg",
        "country": "Germany",
        "league": "Bundesliga",
        "city": "Freiburg",
        "lat": 47.999,
        "lon": 7.8421,
        "founded": 1904,
        "stadium": "Europa-Park Stadion",
        "trophies": "2. Bundesliga: 4",
        "mustKnowFact": "Black Forest overachievers.",
        "active": true,
        "logo": "logos/freiburg.png",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Fulham",
        "country": "England",
        "league": "Premier League",
        "city": "London",
        "lat": 51.475,
        "lon": -0.2216,
        "founded": 1879,
        "stadium": "Craven Cottage",
        "trophies": "Championship: 3, League One: 1",
        "mustKnowFact": "Riverside charm lives on.",
        "active": true,
        "logo": "logos/fulham.png",
        "uniform": "uniforms/fulham.png"
    },
    {
        "name": "Genoa",
        "country": "Italy",
        "league": "Serie A",
        "city": "Genoa",
        "lat": 44.4056,
        "lon": 8.9463,
        "founded": 1893,
        "stadium": "Stadio Luigi Ferraris",
        "trophies": "Serie A: 9, Coppa Italia: 1, Serie B: 6",
        "mustKnowFact": "Italy's oldest club.",
        "active": true,
        "logo": "logos/genoa.png",
        "uniform": "uniforms/genoa.png"
    },
    {
        "name": "Getafe",
        "country": "Spain",
        "league": "La Liga",
        "city": "Getafe",
        "lat": 40.3083,
        "lon": -3.7328,
        "founded": 1983,
        "stadium": "Coliseum Alfonso Perez",
        "trophies": "",
        "mustKnowFact": "Madrid's gritty underdogs.",
        "active": true,
        "logo": "logos/getafe.png",
        "uniform": "uniforms/getafe.png"
    },
    {
        "name": "Gil Vicente",
        "country": "Portugal",
        "league": "Primeira Liga",
        "city": "Barcelos",
        "lat": 41.5317,
        "lon": -8.6189,
        "founded": 1924,
        "stadium": "Estadio Cidade de Barcelos",
        "trophies": "",
        "mustKnowFact": "Roosters crow in Barcelos.",
        "active": true,
        "logo": "logos/gil_vicente.png",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Gimnasia y Esgrima La Plata",
        "country": "Argentina",
        "league": "Primera División",
        "city": "La Plata",
        "lat": -34.9205,
        "lon": -57.9916,
        "founded": 1887,
        "stadium": "Estadio Juan Carmelo Zerillo",
        "trophies": "Primera División: 1, Copa Centenario: 1",
        "mustKnowFact": "Oldest club in Argentina.",
        "active": true,
        "logo": "https://via.placeholder.com/200?text=Logo",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Girona",
        "country": "Spain",
        "league": "La Liga",
        "city": "Girona",
        "lat": 41.9794,
        "lon": 2.8214,
        "founded": 1930,
        "stadium": "Montilivi",
        "trophies": "Segunda División: 1",
        "mustKnowFact": "City Football Group's Catalan star.",
        "active": true,
        "logo": "logos/girona.png",
        "uniform": "uniforms/girona.png"
    },
    {
        "name": "Godoy Cruz",
        "country": "Argentina",
        "league": "Primera División",
        "city": "Mendoza",
        "lat": -32.8895,
        "lon": -68.844,
        "founded": 1921,
        "stadium": "Estadio Malvinas Argentinas",
        "trophies": "Primera B Nacional: 1",
        "mustKnowFact": "Mendoza's football heartbeat.",
        "active": true,
        "logo": "logos/godoy_cruz.png",
        "uniform": "uniforms/godoy_cruz.png"
    },
    {
        "name": "Gremio",
        "country": "Brazil",
        "league": "Serie A",
        "city": "Porto Alegre",
        "lat": -30.0346,
        "lon": -51.2177,
        "founded": 1903,
        "stadium": "Arena do Gremio",
        "trophies": "Série A: 2, Copa do Brasil: 5, Campeonato Gaúcho: 42, Copa Libertadores: 3, Intercontinental Cup: 1",
        "mustKnowFact": "Imortal Tricolor fights on.",
        "active": true,
        "logo": "logos/gremio.png",
        "uniform": "uniforms/gremio.png"
    },
    {
        "name": "Hamburg SV",
        "country": "Germany",
        "league": "Bundesliga",
        "city": "Hamburg",
        "lat": 53.5488,
        "lon": 9.9937,
        "founded": 1887,
        "stadium": "Volksparkstadion",
        "trophies": "Bundesliga: 6, DFB-Pokal: 3, European Cup: 1, UEFA Cup Winners' Cup: 1",
        "mustKnowFact": "Northern giants aim back.",
        "active": true,
        "logo": "https://via.placeholder.com/200?text=Logo",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Heidenheim",
        "country": "Germany",
        "league": "Bundesliga",
        "city": "Heidenheim",
        "lat": 48.676,
        "lon": 10.1545,
        "founded": 1846,
        "stadium": "Voith-Arena",
        "trophies": "2. Bundesliga: 1",
        "mustKnowFact": "Tiny town's big dream.",
        "active": true,
        "logo": "https://via.placeholder.com/200?text=Logo",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Hellas Verona",
        "country": "Italy",
        "league": "Serie A",
        "city": "Verona",
        "lat": 45.4384,
        "lon": 10.9916,
        "founded": 1903,
        "stadium": "Stadio Marcantonio Bentegodi",
        "trophies": "Serie A: 1, Serie B: 3",
        "mustKnowFact": "1985's shock Scudetto.",
        "active": true,
        "logo": "https://via.placeholder.com/200?text=Logo",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Hoffenheim",
        "country": "Germany",
        "league": "Bundesliga",
        "city": "Sinsheim",
        "lat": 49.2529,
        "lon": 8.887,
        "founded": 1899,
        "stadium": "PreZero Arena",
        "trophies": "",
        "mustKnowFact": "Village club's miracle.",
        "active": true,
        "logo": "logos/hoffenheim.png",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Holstein Kiel",
        "country": "Germany",
        "league": "Bundesliga",
        "city": "Kiel",
        "lat": 54.3233,
        "lon": 10.1228,
        "founded": 1900,
        "stadium": "Holstein-Stadion",
        "trophies": "3. Liga: 1",
        "mustKnowFact": "Northern newcomers in 2024.",
        "active": true,
        "logo": "logos/holstein_kiel.png",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Huracán",
        "country": "Argentina",
        "league": "Primera División",
        "city": "Buenos Aires",
        "lat": -34.6431,
        "lon": -58.3976,
        "founded": 1908,
        "stadium": "Estadio Tomás Adolfo Ducó",
        "trophies": "Primera División: 5",
        "mustKnowFact": "The Balloon flies in Parque Patricios.",
        "active": true,
        "logo": "logos/huracan.png",
        "uniform": "uniforms/huracan.png"
    },
    {
        "name": "Independiente",
        "country": "Argentina",
        "league": "Primera División",
        "city": "Avellaneda",
        "lat": -34.6703,
        "lon": -58.371,
        "founded": 1905,
        "stadium": "Estadio Libertadores de América",
        "trophies": "Primera División: 16, Copa Libertadores: 7, Intercontinental Cup: 2, Copa Sudamericana: 2, Recopa Sudamericana: 1, Supercopa Libertadores: 1",
        "mustKnowFact": "Record seven Libertadores titles.",
        "active": true,
        "logo": "logos/independiente.png",
        "uniform": "uniforms/independiente.png"
    },
    {
        "name": "Instituto ACC",
        "country": "Argentina",
        "league": "Primera División",
        "city": "Córdoba",
        "lat": -31.4167,
        "lon": -64.1833,
        "founded": 1918,
        "stadium": "Estadio Juan Domingo Perón",
        "trophies": "Primera B Nacional: 2",
        "mustKnowFact": "Córdoba's academic fighters.",
        "active": true,
        "logo": "https://via.placeholder.com/200?text=Logo",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Inter Milan",
        "country": "Italy",
        "league": "Serie A",
        "city": "Milan",
        "lat": 45.4642,
        "lon": 9.19,
        "founded": 1908,
        "stadium": "San Siro",
        "trophies": "Serie A: 19, Coppa Italia: 9, Supercoppa Italiana: 8, Champions League: 3, UEFA Cup: 3, Intercontinental Cup: 2",
        "mustKnowFact": "The Nerazzurri's treble in 2010.",
        "active": true,
        "logo": "logos/inter_milan.png",
        "uniform": "uniforms/inter_milan.png"
    },
    {
        "name": "Internacional",
        "country": "Brazil",
        "league": "Serie A",
        "city": "Porto Alegre",
        "lat": -30.0655,
        "lon": -51.235,
        "founded": 1909,
        "stadium": "Beira-Rio",
        "trophies": "Série A: 3, Copa do Brasil: 1, Campeonato Gaúcho: 45, Copa Libertadores: 2, Club World Cup: 1",
        "mustKnowFact": "Colorado giants rise.",
        "active": true,
        "logo": "logos/internacional.png",
        "uniform": "uniforms/internacional.png"
    },
    {
        "name": "Ipswich Town",
        "country": "England",
        "league": "Premier League",
        "city": "Ipswich",
        "lat": 52.055,
        "lon": 1.145,
        "founded": 1878,
        "stadium": "Portman Road",
        "trophies": "First Division: 1, FA Cup: 1, UEFA Cup: 1, Championship: 2",
        "mustKnowFact": "Tractor Boys return.",
        "active": true,
        "logo": "logos/ipswich_town.png",
        "uniform": "uniforms/ipswich_town.png"
    },
    {
        "name": "Juventude",
        "country": "Brazil",
        "league": "Serie A",
        "city": "Caxias do Sul",
        "lat": -29.1681,
        "lon": -51.1794,
        "founded": 1913,
        "stadium": "Alfredo Jaconi",
        "trophies": "Série B: 1, Copa do Brasil: 1, Campeonato Gaúcho: 1",
        "mustKnowFact": "Green resurgence in Serie A.",
        "active": true,
        "logo": "logos/juventude.png",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Juventus",
        "country": "Italy",
        "league": "Serie A",
        "city": "Turin",
        "lat": 45.0703,
        "lon": 7.6869,
        "founded": 1897,
        "stadium": "Allianz Stadium",
        "trophies": "Serie A: 36, Coppa Italia: 15, Supercoppa Italiana: 9, Champions League: 2, UEFA Cup: 3, UEFA Cup Winners' Cup: 1, UEFA Super Cup: 2, Intercontinental Cup: 2",
        "mustKnowFact": "Italy's most successful club.",
        "active": true,
        "logo": "logos/juventus.png",
        "uniform": "uniforms/juventus.png"
    },
    {
        "name": "Koln",
        "country": "Germany",
        "league": "Bundesliga",
        "city": "Cologne",
        "lat": 50.9375,
        "lon": 6.9603,
        "founded": 1948,
        "stadium": "RheinEnergieStadion",
        "trophies": "Bundesliga: 3, DFB-Pokal: 4, 2. Bundesliga: 4",
        "mustKnowFact": "The Billy Goats' spirit.",
        "active": true,
        "logo": "https://via.placeholder.com/200?text=Logo",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Lanús",
        "country": "Argentina",
        "league": "Primera División",
        "city": "Lanús",
        "lat": -34.7172,
        "lon": -58.3849,
        "founded": 1915,
        "stadium": "Estadio Ciudad de Lanús",
        "trophies": "Primera División: 2, Copa Sudamericana: 1, Supercopa Argentina: 1, Primera B Nacional: 1",
        "mustKnowFact": "Granate's suburban success.",
        "active": true,
        "logo": "https://via.placeholder.com/200?text=Logo",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Las Palmas",
        "country": "Spain",
        "league": "La Liga",
        "city": "Las Palmas",
        "lat": 28.1235,
        "lon": -15.4363,
        "founded": 1949,
        "stadium": "Gran Canaria",
        "trophies": "Segunda División: 2",
        "mustKnowFact": "Canary Islands' sunny flair.",
        "active": true,
        "logo": "logos/las_palmas.png",
        "uniform": "uniforms/las_palmas.png"
    },
    {
        "name": "Lazio",
        "country": "Italy",
        "league": "Serie A",
        "city": "Rome",
        "lat": 41.9028,
        "lon": 12.4964,
        "founded": 1900,
        "stadium": "Stadio Olimpico",
        "trophies": "Serie A: 2, Coppa Italia: 7, Supercoppa Italiana: 5, UEFA Cup Winners' Cup: 1, UEFA Super Cup: 1",
        "mustKnowFact": "Eagles of Rome soar.",
        "active": true,
        "logo": "logos/lazio.png",
        "uniform": "uniforms/lazio.png"
    },
    {
        "name": "Le Havre AC",
        "country": "France",
        "league": "Ligue 1",
        "city": "Le Havre",
        "lat": 49.4988,
        "lon": 0.1267,
        "founded": 1872,
        "stadium": "Stade Océane",
        "trophies": "Ligue 1: 0, Coupe de France: 1, Ligue 2: 6",
        "mustKnowFact": "Oldest club in France, steady in Ligue 1.",
        "active": true,
        "logo": "https://via.placeholder.com/200?text=Logo",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Lecce",
        "country": "Italy",
        "league": "Serie A",
        "city": "Lecce",
        "lat": 40.3515,
        "lon": 18.158,
        "founded": 1908,
        "stadium": "Stadio Via del Mare",
        "trophies": "Serie B: 2",
        "mustKnowFact": "Apulia's yellow-and-red.",
        "active": true,
        "logo": "logos/lecce.png",
        "uniform": "uniforms/lecce.png"
    },
    {
        "name": "Leganes",
        "country": "Spain",
        "league": "La Liga",
        "city": "Leganes",
        "lat": 40.3302,
        "lon": -3.768,
        "founded": 1928,
        "stadium": "Butarque",
        "trophies": "",
        "mustKnowFact": "Madrid's southern minnows.",
        "active": true,
        "logo": "logos/leganes.png",
        "uniform": "uniforms/leganes.png"
    },
    {
        "name": "Leicester City",
        "country": "England",
        "league": "Premier League",
        "city": "Leicester",
        "lat": 52.6203,
        "lon": -1.1422,
        "founded": 1884,
        "stadium": "King Power Stadium",
        "trophies": "Premier League: 1, FA Cup: 1, League Cup: 3, Community Shield: 2, Championship: 7",
        "mustKnowFact": "2016's fairy-tale champs.",
        "active": true,
        "logo": "logos/leicester_city.png",
        "uniform": "uniforms/leicester_city.png"
    },
    {
        "name": "Lille OSC",
        "country": "France",
        "league": "Ligue 1",
        "city": "Lille",
        "lat": 50.6119,
        "lon": 3.1305,
        "founded": 1944,
        "stadium": "Stade Pierre-Mauroy",
        "trophies": "Ligue 1: 4, Coupe de France: 6, Trophée des Champions: 1, Ligue 2: 5",
        "mustKnowFact": "2021 Ligue 1 champs holding strong.",
        "active": true,
        "logo": "logos/lille_osc.png",
        "uniform": "uniforms/lille_osc.png"
    },
    {
        "name": "Liverpool",
        "country": "England",
        "league": "Premier League",
        "city": "Liverpool",
        "lat": 53.4308,
        "lon": -2.9608,
        "founded": 1892,
        "stadium": "Anfield",
        "trophies": "Premier League: 1, First Division: 18, FA Cup: 8, League Cup: 10, Community Shield: 16, European Cup/Champions League: 6, UEFA Cup/Europa League: 3, UEFA Super Cup: 4",
        "mustKnowFact": "You'll Never Walk Alone anthem.",
        "active": true,
        "logo": "logos/liverpool.png",
        "uniform": "uniforms/liverpool.png"
    },
    {
        "name": "Mainz 05",
        "country": "Germany",
        "league": "Bundesliga",
        "city": "Mainz",
        "lat": 49.9929,
        "lon": 8.2473,
        "founded": 1905,
        "stadium": "Mewa Arena",
        "trophies": "",
        "mustKnowFact": "Carnival club's grit.",
        "active": true,
        "logo": "https://via.placeholder.com/200?text=Logo",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Mallorca",
        "country": "Spain",
        "league": "La Liga",
        "city": "Palma",
        "lat": 39.5696,
        "lon": 2.6502,
        "founded": 1916,
        "stadium": "Son Moix",
        "trophies": "Copa del Rey: 1, Supercopa de España: 1, Segunda División: 2",
        "mustKnowFact": "Island grit in La Liga.",
        "active": true,
        "logo": "logos/mallorca.png",
        "uniform": "uniforms/mallorca.png"
    },
    {
        "name": "Manchester City",
        "country": "England",
        "league": "Premier League",
        "city": "Manchester",
        "lat": 53.483,
        "lon": -2.2004,
        "founded": 1880,
        "stadium": "Etihad Stadium",
        "trophies": "Premier League: 10, First Division: 2, FA Cup: 7, League Cup: 8, Community Shield: 6, Champions League: 1, UEFA Cup Winners' Cup: 1",
        "mustKnowFact": "Pep's tactical revolution.",
        "active": true,
        "logo": "logos/manchester_city.png",
        "uniform": "uniforms/manchester_city.png"
    },
    {
        "name": "Manchester United",
        "country": "England",
        "league": "Premier League",
        "city": "Manchester",
        "lat": 53.4831,
        "lon": -2.2446,
        "founded": 1878,
        "stadium": "Old Trafford",
        "trophies": "Premier League: 13, First Division: 7, FA Cup: 13, League Cup: 6, Community Shield: 21, Champions League: 3, Europa League: 1, UEFA Cup Winners' Cup: 1, UEFA Super Cup: 1",
        "mustKnowFact": "Global fanbase giants.",
        "active": true,
        "logo": "logos/manchester_united.png",
        "uniform": "uniforms/manchester_united.png"
    },
    {
        "name": "Maritimo",
        "country": "Portugal",
        "league": "Primeira Liga",
        "city": "Funchal",
        "lat": 32.6702,
        "lon": -16.9241,
        "founded": 1910,
        "stadium": "Estadio do Maritimo",
        "trophies": "Taça de Portugal: 1",
        "mustKnowFact": "Madeira's green-and-red.",
        "active": true,
        "logo": "https://via.placeholder.com/200?text=Logo",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Montpellier HSC",
        "country": "France",
        "league": "Ligue 1",
        "city": "Montpellier",
        "lat": 43.6119,
        "lon": 3.8767,
        "founded": 1919,
        "stadium": "Stade de la Mosson",
        "trophies": "Ligue 1: 1, Coupe de France: 2, Coupe de la Ligue: 1, Ligue 2: 4",
        "mustKnowFact": "2012 Ligue 1 title remains their peak.",
        "active": true,
        "logo": "logos/montpellier_hsc.png",
        "uniform": "uniforms/montpellier_hsc.png"
    },
    {
        "name": "Monza",
        "country": "Italy",
        "league": "Serie A",
        "city": "Monza",
        "lat": 45.5845,
        "lon": 9.2749,
        "founded": 1912,
        "stadium": "U-Power Stadium",
        "trophies": "Serie B: 4",
        "mustKnowFact": "Berlusconi's late project.",
        "active": true,
        "logo": "logos/monza.png",
        "uniform": "uniforms/monza.png"
    },
    {
        "name": "Moreirense",
        "country": "Portugal",
        "league": "Primeira Liga",
        "city": "Moreira de Conegos",
        "lat": 41.3858,
        "lon": -8.3398,
        "founded": 1938,
        "stadium": "Parque de Jogos Comendador Joaquim de Almeida Freitas",
        "trophies": "Taça da Liga: 1",
        "mustKnowFact": "Small town, big heart.",
        "active": true,
        "logo": "logos/moreirense.png",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Nacional",
        "country": "Portugal",
        "league": "Primeira Liga",
        "city": "Funchal",
        "lat": 32.6702,
        "lon": -16.9241,
        "founded": 1910,
        "stadium": "Estadio da Madeira",
        "trophies": "",
        "mustKnowFact": "Madeira's black-and-white.",
        "active": true,
        "logo": "https://via.placeholder.com/200?text=Logo",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Napoli",
        "country": "Italy",
        "league": "Serie A",
        "city": "Naples",
        "lat": 40.8518,
        "lon": 14.2681,
        "founded": 1926,
        "stadium": "Stadio Diego Armando Maradona",
        "trophies": "Serie A: 3, Coppa Italia: 6, Supercoppa Italiana: 2, UEFA Cup: 1",
        "mustKnowFact": "Maradona's Naples legacy.",
        "active": true,
        "logo": "logos/napoli.png",
        "uniform": "uniforms/napoli.png"
    },
    {
        "name": "Newcastle United",
        "country": "England",
        "league": "Premier League",
        "city": "Newcastle",
        "lat": 54.9756,
        "lon": -1.6216,
        "founded": 1892,
        "stadium": "St James' Park",
        "trophies": "First Division: 4, FA Cup: 6, Community Shield: 1, Championship: 4",
        "mustKnowFact": "Geordie passion runs wild.",
        "active": true,
        "logo": "logos/newcastle_united.png",
        "uniform": "uniforms/newcastle_united.png"
    },
    {
        "name": "Newell's Old Boys",
        "country": "Argentina",
        "league": "Primera División",
        "city": "Rosario",
        "lat": -32.9476,
        "lon": -60.6665,
        "founded": 1903,
        "stadium": "Estadio Marcelo Bielsa",
        "trophies": "Primera División: 6, Primera B Nacional: 1",
        "mustKnowFact": "Messi's childhood heroes.",
        "active": true,
        "logo": "logos/newell's_old_boys.png",
        "uniform": "uniforms/newell's_old_boys.png"
    },
    {
        "name": "Nottingham Forest",
        "country": "England",
        "league": "Premier League",
        "city": "Nottingham",
        "lat": 52.94,
        "lon": -1.137,
        "founded": 1865,
        "stadium": "City Ground",
        "trophies": "First Division: 1, FA Cup: 2, League Cup: 4, Community Shield: 1, European Cup: 2, UEFA Super Cup: 1",
        "mustKnowFact": "Back-to-back European champs.",
        "active": true,
        "logo": "logos/nottingham_forest.png",
        "uniform": "uniforms/nottingham_forest.png"
    },
    {
        "name": "OGC Nice",
        "country": "France",
        "league": "Ligue 1",
        "city": "Nice",
        "lat": 43.7034,
        "lon": 7.2663,
        "founded": 1904,
        "stadium": "Allianz Riviera",
        "trophies": "Ligue 1: 4, Coupe de France: 3, Trophée des Champions: 1, Ligue 2: 4",
        "mustKnowFact": "Riviera club with INEOS backing.",
        "active": true,
        "logo": "logos/ogc_nice.png",
        "uniform": "uniforms/ogc_nice.png"
    },
    {
        "name": "Olympique Lyonnais",
        "country": "France",
        "league": "Ligue 1",
        "city": "Lyon",
        "lat": 45.7238,
        "lon": 4.832,
        "founded": 1950,
        "stadium": "Groupama Stadium",
        "trophies": "Ligue 1: 7, Coupe de France: 5, Coupe de la Ligue: 1, Trophée des Champions: 8, Ligue 2: 3",
        "mustKnowFact": "Early 2000s dominance fading but still fierce.",
        "active": true,
        "logo": "logos/olympique_lyonnais.png",
        "uniform": "uniforms/olympique_lyonnais.png"
    },
    {
        "name": "Olympique Marseille",
        "country": "France",
        "league": "Ligue 1",
        "city": "Marseille",
        "lat": 43.27,
        "lon": 5.3959,
        "founded": 1899,
        "stadium": "Stade Vélodrome",
        "trophies": "Ligue 1: 9, Champions League: 1, Coupe de France: 10, Coupe de la Ligue: 3, Trophée des Champions: 3, Ligue 2: 1",
        "mustKnowFact": "France's only Champions League winner (1993).",
        "active": true,
        "logo": "https://via.placeholder.com/200?text=Logo",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Osasuna",
        "country": "Spain",
        "league": "La Liga",
        "city": "Pamplona",
        "lat": 42.8188,
        "lon": -1.6458,
        "founded": 1920,
        "stadium": "El Sadar",
        "trophies": "Segunda División: 4",
        "mustKnowFact": "Navarre's red warriors.",
        "active": true,
        "logo": "logos/osasuna.png",
        "uniform": "uniforms/osasuna.png"
    },
    {
        "name": "Palmeiras",
        "country": "Brazil",
        "league": "Serie A",
        "city": "Sao Paulo",
        "lat": -23.5489,
        "lon": -46.6388,
        "founded": 1914,
        "stadium": "Allianz Parque",
        "trophies": "Série A: 12, Copa do Brasil: 4, Campeonato Paulista: 25, Copa Libertadores: 3, Intercontinental Cup: 1",
        "mustKnowFact": "First club world champs.",
        "active": true,
        "logo": "logos/palmeiras.png",
        "uniform": "uniforms/palmeiras.png"
    },
    {
        "name": "Paris Saint-Germain",
        "country": "France",
        "league": "Ligue 1",
        "city": "Paris",
        "lat": 48.8414,
        "lon": 2.253,
        "founded": 1970,
        "stadium": "Parc des Princes",
        "trophies": "Ligue 1: 12, Coupe de France: 15, Coupe de la Ligue: 10, Trophée des Champions: 12, Ligue 2: 1, UEFA Cup Winners' Cup: 1",
        "mustKnowFact": "2024 Trophée des Champions winners over Monaco.",
        "active": true,
        "logo": "https://via.placeholder.com/200?text=Logo",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Parma",
        "country": "Italy",
        "league": "Serie A",
        "city": "Parma",
        "lat": 44.8015,
        "lon": 10.328,
        "founded": 1913,
        "stadium": "Stadio Ennio Tardini",
        "trophies": "Coppa Italia: 3, UEFA Cup: 2, UEFA Cup Winners' Cup: 1, UEFA Super Cup: 1, Serie B: 4",
        "mustKnowFact": "90s European glory.",
        "active": true,
        "logo": "https://via.placeholder.com/200?text=Logo",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Platense",
        "country": "Argentina",
        "league": "Primera División",
        "city": "Buenos Aires",
        "lat": -34.5833,
        "lon": -58.4167,
        "founded": 1905,
        "stadium": "Estadio Ciudad de Vicente López",
        "trophies": "Primera B Metropolitana: 1",
        "mustKnowFact": "The Squid's steady rise.",
        "active": true,
        "logo": "logos/platense.png",
        "uniform": "uniforms/platense.png"
    },
    {
        "name": "Porto",
        "country": "Portugal",
        "league": "Primeira Liga",
        "city": "Porto",
        "lat": 41.1579,
        "lon": -8.6291,
        "founded": 1893,
        "stadium": "Estadio do Dragao",
        "trophies": "Primeira Liga: 30, Taça de Portugal: 19, Taça da Liga: 1, Supertaça Cândido de Oliveira: 23, Champions League: 2, UEFA Cup/Europa League: 2, UEFA Super Cup: 1, Intercontinental Cup: 2",
        "mustKnowFact": "Dragons' European glory.",
        "active": true,
        "logo": "logos/porto.png",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "RB Leipzig",
        "country": "Germany",
        "league": "Bundesliga",
        "city": "Leipzig",
        "lat": 51.3397,
        "lon": 12.3731,
        "founded": 2009,
        "stadium": "Red Bull Arena",
        "trophies": "DFB-Pokal: 2, DFL-Supercup: 1",
        "mustKnowFact": "Red Bull's rapid rise.",
        "active": true,
        "logo": "logos/rb_leipzig.png",
        "uniform": "uniforms/rb_leipzig.png"
    },
    {
        "name": "RC Lens",
        "country": "France",
        "league": "Ligue 1",
        "city": "Lens",
        "lat": 50.4322,
        "lon": 2.8318,
        "founded": 1906,
        "stadium": "Stade Bollaert-Delelis",
        "trophies": "Ligue 1: 1, Coupe de la Ligue: 1, Ligue 2: 4",
        "mustKnowFact": "Coal town's red-and-yellow resurgence.",
        "active": true,
        "logo": "logos/rc_lens.png",
        "uniform": "uniforms/rc_lens.png"
    },
    {
        "name": "RC Strasbourg Alsace",
        "country": "France",
        "league": "Ligue 1",
        "city": "Strasbourg",
        "lat": 48.5846,
        "lon": 7.736,
        "founded": 1906,
        "stadium": "Stade de la Meinau",
        "trophies": "Ligue 1: 1, Coupe de France: 3, Coupe de la Ligue: 3, Ligue 2: 1",
        "mustKnowFact": "Alsace's blue-and-white pride.",
        "active": true,
        "logo": "https://via.placeholder.com/200?text=Logo",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Racing Club",
        "country": "Argentina",
        "league": "Primera División",
        "city": "Avellaneda",
        "lat": -34.6675,
        "lon": -58.3686,
        "founded": 1903,
        "stadium": "Estadio Presidente Perón",
        "trophies": "Primera División: 18, Copa Libertadores: 1, Intercontinental Cup: 1, Supercopa Argentina: 1",
        "mustKnowFact": "The Academy's trophy-laden history.",
        "active": true,
        "logo": "logos/racing_club.png",
        "uniform": "uniforms/racing_club.png"
    },
    {
        "name": "Rayo Vallecano",
        "country": "Spain",
        "league": "La Liga",
        "city": "Madrid",
        "lat": 40.3919,
        "lon": -3.6588,
        "founded": 1924,
        "stadium": "Vallecas",
        "trophies": "Segunda División: 1",
        "mustKnowFact": "Vallecas' working-class heroes.",
        "active": true,
        "logo": "https://via.placeholder.com/200?text=Logo",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Real Betis",
        "country": "Spain",
        "league": "La Liga",
        "city": "Seville",
        "lat": 37.3891,
        "lon": -5.9845,
        "founded": 1907,
        "stadium": "Benito Villamarin",
        "trophies": "La Liga: 1, Copa del Rey: 3, Segunda División: 7",
        "mustKnowFact": "Green and white fervor.",
        "active": true,
        "logo": "logos/real_betis.png",
        "uniform": "uniforms/real_betis.png"
    },
    {
        "name": "Real Madrid",
        "country": "Spain",
        "league": "La Liga",
        "city": "Madrid",
        "lat": 40.4168,
        "lon": -3.7038,
        "founded": 1902,
        "stadium": "Santiago Bernabeu",
        "trophies": "La Liga: 35, Copa del Rey: 20, Supercopa de España: 13, Champions League: 15, UEFA Cup: 2, UEFA Super Cup: 5, Club World Cup: 5",
        "mustKnowFact": "Most Champions League titles in history.",
        "active": true,
        "logo": "logos/real_madrid.png",
        "uniform": "uniforms/real_madrid.png"
    },
    {
        "name": "Real Sociedad",
        "country": "Spain",
        "league": "La Liga",
        "city": "San Sebastian",
        "lat": 43.3183,
        "lon": -1.9812,
        "founded": 1909,
        "stadium": "Reale Arena",
        "trophies": "La Liga: 2, Copa del Rey: 2, Supercopa de España: 1, Segunda División: 3",
        "mustKnowFact": "Basque pride runs deep.",
        "active": true,
        "logo": "logos/real_sociedad.png",
        "uniform": "uniforms/real_sociedad.png"
    },
    {
        "name": "Real Valladolid",
        "country": "Spain",
        "league": "La Liga",
        "city": "Valladolid",
        "lat": 41.6523,
        "lon": -4.7245,
        "founded": 1928,
        "stadium": "Jose Zorrilla",
        "trophies": "Segunda División: 3",
        "mustKnowFact": "Ronaldo's ownership dream.",
        "active": true,
        "logo": "logos/real_valladolid.png",
        "uniform": "uniforms/real_valladolid.png"
    },
    {
        "name": "Rio Ave",
        "country": "Portugal",
        "league": "Primeira Liga",
        "city": "Vila do Conde",
        "lat": 41.3006,
        "lon": -8.7352,
        "founded": 1939,
        "stadium": "Estadio dos Arcos",
        "trophies": "",
        "mustKnowFact": "River Ave's green stripes.",
        "active": true,
        "logo": "logos/rio_ave.png",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "River Plate",
        "country": "Argentina",
        "league": "Primera División",
        "city": "Buenos Aires",
        "lat": -34.5453,
        "lon": -58.4498,
        "founded": 1901,
        "stadium": "Estadio Monumental",
        "trophies": "Primera División: 38, Copa Libertadores: 4, Intercontinental Cup: 1, Copa Sudamericana: 1, Recopa Sudamericana: 3, Supercopa Argentina: 3, Copa Argentina: 3",
        "mustKnowFact": "Argentina's trophy kings.",
        "active": true,
        "logo": "logos/river_plate.png",
        "uniform": "uniforms/river_plate.png"
    },
    {
        "name": "Rosario Central",
        "country": "Argentina",
        "league": "Primera División",
        "city": "Rosario",
        "lat": -32.9507,
        "lon": -60.6665,
        "founded": 1889,
        "stadium": "Estadio Gigante de Arroyito",
        "trophies": "Primera División: 4, Copa CONMEBOL: 1, Copa Argentina: 1, Primera B Nacional: 2",
        "mustKnowFact": "Rosario's blue-and-yellow soul.",
        "active": true,
        "logo": "logos/rosario_central.png",
        "uniform": "uniforms/rosario_central.png"
    },
    {
        "name": "Salernitana",
        "country": "Italy",
        "league": "Serie A",
        "city": "Salerno",
        "lat": 40.6824,
        "lon": 14.7681,
        "founded": 1919,
        "stadium": "Stadio Arechi",
        "trophies": "Serie B: 2",
        "mustKnowFact": "Granata's southern spirit.",
        "active": true,
        "logo": "logos/salernitana.png",
        "uniform": "uniforms/salernitana.png"
    },
    {
        "name": "San Lorenzo",
        "country": "Argentina",
        "league": "Primera División",
        "city": "Buenos Aires",
        "lat": -34.6372,
        "lon": -58.4029,
        "founded": 1908,
        "stadium": "Estadio Pedro Bidegain",
        "trophies": "Primera División: 15, Copa Libertadores: 1, Copa Sudamericana: 1, Supercopa Argentina: 1",
        "mustKnowFact": "Pope Francis cheers for them.",
        "active": true,
        "logo": "logos/san_lorenzo.png",
        "uniform": "uniforms/san_lorenzo.png"
    },
    {
        "name": "Santa Clara",
        "country": "Portugal",
        "league": "Primeira Liga",
        "city": "Ponta Delgada",
        "lat": 37.7388,
        "lon": -25.668,
        "founded": 1927,
        "stadium": "Estadio de Sao Miguel",
        "trophies": "",
        "mustKnowFact": "Azores' lone warriors.",
        "active": true,
        "logo": "logos/santa_clara.png",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Santos FC",
        "country": "Brazil",
        "league": "Serie A",
        "city": "Santos",
        "lat": -23.5505,
        "lon": -46.6333,
        "founded": 1912,
        "stadium": "Vila Belmiro",
        "trophies": "Série A: 7, Copa do Brasil: 1, Campeonato Paulista: 22, Copa Libertadores: 3, Intercontinental Cup: 2",
        "mustKnowFact": "Pele's iconic home.",
        "active": true,
        "logo": "https://via.placeholder.com/200?text=Logo",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Sao Paulo",
        "country": "Brazil",
        "league": "Serie A",
        "city": "Sao Paulo",
        "lat": -23.5489,
        "lon": -46.6388,
        "founded": 1930,
        "stadium": "Morumbi",
        "trophies": "Série A: 6, Copa do Brasil: 1, Campeonato Paulista: 22, Copa Libertadores: 3, Intercontinental Cup: 3",
        "mustKnowFact": "Three-time world champs.",
        "active": true,
        "logo": "logos/sao_paulo.png",
        "uniform": "uniforms/sao_paulo.png"
    },
    {
        "name": "Sarmiento",
        "country": "Argentina",
        "league": "Primera División",
        "city": "Juní­n",
        "lat": -34.5833,
        "lon": -60.95,
        "founded": 1911,
        "stadium": "Estadio Eva Perón",
        "trophies": "Primera B Nacional: 1",
        "mustKnowFact": "Juní­n's green resilience.",
        "active": true,
        "logo": "logos/sarmiento.png",
        "uniform": "uniforms/sarmiento.png"
    },
    {
        "name": "Sassuolo",
        "country": "Italy",
        "league": "Serie A",
        "city": "Sassuolo",
        "lat": 44.5442,
        "lon": 10.7848,
        "founded": 1920,
        "stadium": "Mapei Stadium",
        "trophies": "",
        "mustKnowFact": "Green-and-black overachievers.",
        "active": true,
        "logo": "logos/sassuolo.png",
        "uniform": "uniforms/sassuolo.png"
    },
    {
        "name": "Schalke 04",
        "country": "Germany",
        "league": "Bundesliga",
        "city": "Gelsenkirchen",
        "lat": 51.555,
        "lon": 7.0665,
        "founded": 1904,
        "stadium": "Veltins-Arena",
        "trophies": "Bundesliga: 7, DFB-Pokal: 5, DFL-Supercup: 1, UEFA Cup: 1",
        "mustKnowFact": "Miners' blue legacy.",
        "active": true,
        "logo": "logos/schalke_04.png",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Sevilla",
        "country": "Spain",
        "league": "La Liga",
        "city": "Seville",
        "lat": 37.3891,
        "lon": -5.9845,
        "founded": 1890,
        "stadium": "Ramon Sanchez Pizjuan",
        "trophies": "La Liga: 1, Copa del Rey: 5, Supercopa de España: 1, Europa League: 7, UEFA Super Cup: 1",
        "mustKnowFact": "Europa League masters.",
        "active": true,
        "logo": "logos/sevilla.png",
        "uniform": "uniforms/sevilla.png"
    },
    {
        "name": "Southampton",
        "country": "England",
        "league": "Premier League",
        "city": "Southampton",
        "lat": 50.9059,
        "lon": -1.391,
        "founded": 1885,
        "stadium": "St Mary's",
        "trophies": "FA Cup: 1, League Cup: 1, Third Division: 1",
        "mustKnowFact": "Saints march back up.",
        "active": true,
        "logo": "logos/southampton.png",
        "uniform": "uniforms/southampton.png"
    },
    {
        "name": "Sporting CP",
        "country": "Portugal",
        "league": "Primeira Liga",
        "city": "Lisbon",
        "lat": 38.7223,
        "lon": -9.1393,
        "founded": 1906,
        "stadium": "Estadio Jose Alvalade",
        "trophies": "Primeira Liga: 19, Taça de Portugal: 17, Taça da Liga: 4, Supertaça Cândido de Oliveira: 9",
        "mustKnowFact": "Lions roar in green.",
        "active": true,
        "logo": "logos/sporting_cp.png",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Stade Brestois 29",
        "country": "France",
        "league": "Ligue 1",
        "city": "Brest",
        "lat": 48.3904,
        "lon": -4.4861,
        "founded": 1950,
        "stadium": "Stade Francis-Le Blé",
        "trophies": "Ligue 2: 2",
        "mustKnowFact": "Earned a Champions League spot in 2023-24.",
        "active": true,
        "logo": "logos/stade_brestois_29.png",
        "uniform": "uniforms/stade_brestois_29.png"
    },
    {
        "name": "Stade Rennais",
        "country": "France",
        "league": "Ligue 1",
        "city": "Rennes",
        "lat": 48.1147,
        "lon": -1.6794,
        "founded": 1901,
        "stadium": "Roazhon Park",
        "trophies": "Coupe de France: 3, Ligue 2: 2, Trophée des Champions: 1",
        "mustKnowFact": "Brittany's consistent European contenders.",
        "active": true,
        "logo": "logos/stade_rennais.png",
        "uniform": "uniforms/stade_rennais.png"
    },
    {
        "name": "Stade de Reims",
        "country": "France",
        "league": "Ligue 1",
        "city": "Reims",
        "lat": 49.25,
        "lon": 4.0333,
        "founded": 1931,
        "stadium": "Stade Auguste-Delaune",
        "trophies": "Ligue 1: 6, Coupe de France: 2, Trophée des Champions: 4, Ligue 2: 2",
        "mustKnowFact": "1950s European finalists reborn.",
        "active": true,
        "logo": "logos/stade_de_reims.png",
        "uniform": "uniforms/stade_de_reims.png"
    },
    {
        "name": "Talleres",
        "country": "Argentina",
        "league": "Primera División",
        "city": "Córdoba",
        "lat": -31.4167,
        "lon": -64.1833,
        "founded": 1913,
        "stadium": "Estadio Mario Alberto Kempes",
        "trophies": "Primera División: 1, Copa CONMEBOL: 1, Primera B Nacional: 2",
        "mustKnowFact": "Córdoba's modern power.",
        "active": true,
        "logo": "https://via.placeholder.com/200?text=Logo",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Tigre",
        "country": "Argentina",
        "league": "Primera División",
        "city": "Victoria",
        "lat": -34.4167,
        "lon": -58.5833,
        "founded": 1902,
        "stadium": "Estadio José Dellagiovanna",
        "trophies": "Primera B Nacional: 3",
        "mustKnowFact": "Tiger stripes near Buenos Aires.",
        "active": true,
        "logo": "logos/tigre.png",
        "uniform": "uniforms/tigre.png"
    },
    {
        "name": "Torino",
        "country": "Italy",
        "league": "Serie A",
        "city": "Turin",
        "lat": 45.0703,
        "lon": 7.6869,
        "founded": 1906,
        "stadium": "Stadio Olimpico Grande Torino",
        "trophies": "Serie A: 7, Coppa Italia: 5, Serie B: 3",
        "mustKnowFact": "Grande Torino's tragic legacy.",
        "active": true,
        "logo": "logos/torino.png",
        "uniform": "uniforms/torino.png"
    },
    {
        "name": "Tottenham Hotspur",
        "country": "England",
        "league": "Premier League",
        "city": "London",
        "lat": 51.6032,
        "lon": -0.0657,
        "founded": 1882,
        "stadium": "Tottenham Hotspur Stadium",
        "trophies": "First Division: 2, FA Cup: 8, League Cup: 4, Community Shield: 7, UEFA Cup: 2, European Cup Winners' Cup: 1",
        "mustKnowFact": "New stadium, big dreams.",
        "active": true,
        "logo": "logos/tottenham_hotspur.png",
        "uniform": "uniforms/tottenham_hotspur.png"
    },
    {
        "name": "Toulouse FC",
        "country": "France",
        "league": "Ligue 1",
        "city": "Toulouse",
        "lat": 43.5832,
        "lon": 1.434,
        "founded": 1937,
        "stadium": "Stadium de Toulouse",
        "trophies": "Coupe de France: 2, Ligue 2: 4",
        "mustKnowFact": "2023 Coupe de France champs.",
        "active": true,
        "logo": "https://via.placeholder.com/200?text=Logo",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Udinese",
        "country": "Italy",
        "league": "Serie A",
        "city": "Udine",
        "lat": 46.0605,
        "lon": 13.243,
        "founded": 1896,
        "stadium": "Dacia Arena",
        "trophies": "Serie B: 2",
        "mustKnowFact": "Friuli's black-and-white.",
        "active": true,
        "logo": "logos/udinese.png",
        "uniform": "uniforms/udinese.png"
    },
    {
        "name": "Union Berlin",
        "country": "Germany",
        "league": "Bundesliga",
        "city": "Berlin",
        "lat": 52.52,
        "lon": 13.405,
        "founded": 1966,
        "stadium": "Stadion An der Alten Forsterei",
        "trophies": "3. Liga: 1",
        "mustKnowFact": "East Berlin's cult heroes.",
        "active": true,
        "logo": "logos/union_berlin.png",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Unión",
        "country": "Argentina",
        "league": "Primera División",
        "city": "Santa Fe",
        "lat": -31.6333,
        "lon": -60.7,
        "founded": 1907,
        "stadium": "Estadio 15 de Abril",
        "trophies": "Primera B Nacional: 1",
        "mustKnowFact": "Santa Fe's red-and-white faithful.",
        "active": true,
        "logo": "https://via.placeholder.com/200?text=Logo",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Valencia",
        "country": "Spain",
        "league": "La Liga",
        "city": "Valencia",
        "lat": 39.4699,
        "lon": -0.3763,
        "founded": 1919,
        "stadium": "Mestalla",
        "trophies": "La Liga: 6, Copa del Rey: 8, Supercopa de España: 1, UEFA Cup/Europa League: 1, UEFA Cup Winners' Cup: 1, UEFA Super Cup: 1",
        "mustKnowFact": "The bat logo is iconic.",
        "active": true,
        "logo": "logos/valencia.png",
        "uniform": "uniforms/valencia.png"
    },
    {
        "name": "Vasco da Gama",
        "country": "Brazil",
        "league": "Serie A",
        "city": "Rio de Janeiro",
        "lat": -22.8908,
        "lon": -43.228,
        "founded": 1898,
        "stadium": "Sao Januario",
        "trophies": "Série A: 4, Copa do Brasil: 1, Campeonato Carioca: 24, Copa Libertadores: 1",
        "mustKnowFact": "Cross of Malta legacy.",
        "active": true,
        "logo": "logos/vasco_da_gama.png",
        "uniform": "uniforms/vasco_da_gama.png"
    },
    {
        "name": "VfB Stuttgart",
        "country": "Germany",
        "league": "Bundesliga",
        "city": "Stuttgart",
        "lat": 48.7758,
        "lon": 9.1829,
        "founded": 1893,
        "stadium": "Mercedes-Benz Arena",
        "trophies": "Bundesliga: 5, DFB-Pokal: 3, DFL-Supercup: 1, 2. Bundesliga: 2",
        "mustKnowFact": "Swabian pride endures.",
        "active": true,
        "logo": "logos/vfb_stuttgart.png",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Villarreal",
        "country": "Spain",
        "league": "La Liga",
        "city": "Villarreal",
        "lat": 39.9442,
        "lon": -0.1035,
        "founded": 1923,
        "stadium": "Estadio de la Ceramica",
        "trophies": "Europa League: 1",
        "mustKnowFact": "The Yellow Submarine shocked Europe.",
        "active": true,
        "logo": "logos/villarreal.png",
        "uniform": "uniforms/villarreal.png"
    },
    {
        "name": "Vitoria",
        "country": "Brazil",
        "league": "Serie A",
        "city": "Salvador",
        "lat": -12.9714,
        "lon": -38.5014,
        "founded": 1899,
        "stadium": "Barradao",
        "trophies": "Campeonato Baiano: 29, Copa do Nordeste: 4",
        "mustKnowFact": "Red and black revival.",
        "active": true,
        "logo": "logos/vitoria.png",
        "uniform": "uniforms/vitoria.png"
    },
    {
        "name": "Vitoria Guimaraes",
        "country": "Portugal",
        "league": "Primeira Liga",
        "city": "Guimaraes",
        "lat": 41.4425,
        "lon": -8.2938,
        "founded": 1922,
        "stadium": "Estadio D. Afonso Henriques",
        "trophies": "Taça de Portugal: 1, Supertaça Cândido de Oliveira: 1",
        "mustKnowFact": "Conquerors of the north.",
        "active": true,
        "logo": "https://via.placeholder.com/200?text=Logo",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Vélez Sarsfield",
        "country": "Argentina",
        "league": "Primera División",
        "city": "Buenos Aires",
        "lat": -34.635,
        "lon": -58.5228,
        "founded": 1910,
        "stadium": "Estadio José Amalfitani",
        "trophies": "Primera División: 10, Copa Libertadores: 1, Intercontinental Cup: 1, Copa Interamericana: 1, Supercopa Argentina: 1, Recopa Sudamericana: 1",
        "mustKnowFact": "FortÃ­n's blue-and-white fortress.",
        "active": true,
        "logo": "https://via.placeholder.com/200?text=Logo",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Werder Bremen",
        "country": "Germany",
        "league": "Bundesliga",
        "city": "Bremen",
        "lat": 53.0793,
        "lon": 8.8017,
        "founded": 1899,
        "stadium": "Weserstadion",
        "trophies": "Bundesliga: 4, DFB-Pokal: 6, DFL-Supercup: 3, UEFA Cup Winners' Cup: 1, 2. Bundesliga: 1",
        "mustKnowFact": "Green-and-white tradition.",
        "active": true,
        "logo": "logos/werder_bremen.png",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "West Ham United",
        "country": "England",
        "league": "Premier League",
        "city": "London",
        "lat": 51.5319,
        "lon": 0.0394,
        "founded": 1895,
        "stadium": "London Stadium",
        "trophies": "FA Cup: 3, Community Shield: 1, European Cup Winners' Cup: 1, Conference League: 1, Championship: 2",
        "mustKnowFact": "Hammers conquered Europe in 2023.",
        "active": true,
        "logo": "logos/west_ham_united.png",
        "uniform": "uniforms/west_ham_united.png"
    },
    {
        "name": "Wolfsburg",
        "country": "Germany",
        "league": "Bundesliga",
        "city": "Wolfsburg",
        "lat": 52.4245,
        "lon": 10.7867,
        "founded": 1945,
        "stadium": "Volkswagen Arena",
        "trophies": "Bundesliga: 1, DFB-Pokal: 1, DFL-Supercup: 1",
        "mustKnowFact": "VW's football venture.",
        "active": true,
        "logo": "logos/wolfsburg.png",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    },
    {
        "name": "Wolverhampton Wanderers",
        "country": "England",
        "league": "Premier League",
        "city": "Wolverhampton",
        "lat": 52.5902,
        "lon": -2.1305,
        "founded": 1877,
        "stadium": "Molineux",
        "trophies": "First Division: 3, FA Cup: 4, League Cup: 2, Community Shield: 4, Championship: 3",
        "mustKnowFact": "Wolves' golden old days.",
        "active": true,
        "logo": "https://via.placeholder.com/200?text=Logo",
        "uniform": "https://via.placeholder.com/200?text=Uniform"
    }
];
