const teams = [
    // Spain - La Liga (20)
    { name: "Real Madrid", country: "Spain", league: "La Liga", city: "Madrid", lat: 40.4168, lon: -3.7038, founded: 1902, stadium: "Santiago Bernabeu", trophies: 36, funFact: "Most Champions League wins.", active: true },
    { name: "Barcelona", country: "Spain", league: "La Liga", city: "Barcelona", lat: 41.3851, lon: 2.1734, founded: 1899, stadium: "Camp Nou", trophies: 27, funFact: "Messi’s kingdom.", active: true },
    { name: "Atletico Madrid", country: "Spain", league: "La Liga", city: "Madrid", lat: 40.4360, lon: -3.5996, founded: 1903, stadium: "Wanda Metropolitano", trophies: 11, funFact: "Simeone’s fortress.", active: true },
    { name: "Real Sociedad", country: "Spain", league: "La Liga", city: "San Sebastian", lat: 43.3183, lon: -1.9812, founded: 1909, stadium: "Reale Arena", trophies: 2, funFact: "Basque pride.", active: true },
    { name: "Villarreal", country: "Spain", league: "La Liga", city: "Villarreal", lat: 39.9442, lon: -0.1035, founded: 1923, stadium: "Estadio de la Ceramica", trophies: 0, funFact: "Yellow Submarine.", active: true },
    { name: "Real Betis", country: "Spain", league: "La Liga", city: "Seville", lat: 37.3891, lon: -5.9845, founded: 1907, stadium: "Benito Villamarin", trophies: 1, funFact: "Green and white.", active: true },
    { name: "Sevilla", country: "Spain", league: "La Liga", city: "Seville", lat: 37.3891, lon: -5.9845, founded: 1890, stadium: "Ramon Sanchez Pizjuan", trophies: 1, funFact: "Europa League kings.", active: true },
    { name: "Athletic Bilbao", country: "Spain", league: "La Liga", city: "Bilbao", lat: 43.2630, lon: -2.9340, founded: 1898, stadium: "San Mames", trophies: 8, funFact: "Basque-only policy.", active: true },
    { name: "Valencia", country: "Spain", league: "La Liga", city: "Valencia", lat: 39.4699, lon: -0.3763, founded: 1919, stadium: "Mestalla", trophies: 6, funFact: "Bat emblem.", active: true },
    { name: "Getafe", country: "Spain", league: "La Liga", city: "Getafe", lat: 40.3083, lon: -3.7328, founded: 1983, stadium: "Coliseum Alfonso Perez", trophies: 0, funFact: "Madrid’s underdogs.", active: true },
    { name: "Celta Vigo", country: "Spain", league: "La Liga", city: "Vigo", lat: 42.2406, lon: -8.7207, founded: 1923, stadium: "Balaidos", trophies: 0, funFact: "Galician warriors.", active: true },
    { name: "Osasuna", country: "Spain", league: "La Liga", city: "Pamplona", lat: 42.8188, lon: -1.6458, founded: 1920, stadium: "El Sadar", trophies: 0, funFact: "Navarre’s finest.", active: true },
    { name: "Girona", country: "Spain", league: "La Liga", city: "Girona", lat: 41.9794, lon: 2.8214, founded: 1930, stadium: "Montilivi", trophies: 0, funFact: "City Football Group.", active: true },
    { name: "Rayo Vallecano", country: "Spain", league: "La Liga", city: "Madrid", lat: 40.3919, lon: -3.6588, founded: 1924, stadium: "Vallecas", trophies: 0, funFact: "Working-class heroes.", active: true },
    { name: "Mallorca", country: "Spain", league: "La Liga", city: "Palma", lat: 39.5696, lon: 2.6502, founded: 1916, stadium: "Son Moix", trophies: 0, funFact: "Island battlers.", active: true },
    { name: "Espanyol", country: "Spain", league: "La Liga", city: "Barcelona", lat: 41.3478, lon: 2.0757, founded: 1900, stadium: "RCDE Stadium", trophies: 0, funFact: "Barca’s rivals.", active: true },
    { name: "Alaves", country: "Spain", league: "La Liga", city: "Vitoria-Gasteiz", lat: 42.8506, lon: -2.6724, founded: 1921, stadium: "Mendizorrotza", trophies: 0, funFact: "Basque underdogs.", active: true },
    { name: "Leganes", country: "Spain", league: "La Liga", city: "Leganes", lat: 40.3302, lon: -3.7680, founded: 1928, stadium: "Butarque", trophies: 0, funFact: "Madrid’s minnows.", active: true },
    { name: "Real Valladolid", country: "Spain", league: "La Liga", city: "Valladolid", lat: 41.6523, lon: -4.7245, founded: 1928, stadium: "Jose Zorrilla", trophies: 0, funFact: "Ronaldo’s project.", active: true },
    { name: "Las Palmas", country: "Spain", league: "La Liga", city: "Las Palmas", lat: 28.1235, lon: -15.4363, founded: 1949, stadium: "Gran Canaria", trophies: 0, funFact: "Canary Islands pride.", active: true },

    // England - Premier League (20)
    { name: "Manchester United", country: "England", league: "Premier League", city: "Manchester", lat: 53.4831, lon: -2.2446, founded: 1878, stadium: "Old Trafford", trophies: 20, funFact: "The Red Devils.", active: true },
    { name: "Manchester City", country: "England", league: "Premier League", city: "Manchester", lat: 53.4830, lon: -2.2004, founded: 1880, stadium: "Etihad Stadium", trophies: 10, funFact: "Pep’s dynasty.", active: true },
    { name: "Liverpool", country: "England", league: "Premier League", city: "Liverpool", lat: 53.4308, lon: -2.9608, founded: 1892, stadium: "Anfield", trophies: 19, funFact: "You’ll Never Walk Alone.", active: true },
    { name: "Chelsea", country: "England", league: "Premier League", city: "London", lat: 51.4816, lon: -0.1910, founded: 1905, stadium: "Stamford Bridge", trophies: 6, funFact: "Roman’s empire.", active: true },
    { name: "Arsenal", country: "England", league: "Premier League", city: "London", lat: 51.5549, lon: -0.1084, founded: 1886, stadium: "Emirates Stadium", trophies: 13, funFact: "The Invincibles.", active: true },
    { name: "Tottenham Hotspur", country: "England", league: "Premier League", city: "London", lat: 51.6032, lon: -0.0657, founded: 1882, stadium: "Tottenham Hotspur Stadium", trophies: 2, funFact: "Spurs’ new home.", active: true },
    { name: "Newcastle United", country: "England", league: "Premier League", city: "Newcastle", lat: 54.9756, lon: -1.6216, founded: 1892, stadium: "St James’ Park", trophies: 4, funFact: "Geordie giants.", active: true },
    { name: "Aston Villa", country: "England", league: "Premier League", city: "Birmingham", lat: 52.5091, lon: -1.8848, founded: 1874, stadium: "Villa Park", trophies: 7, funFact: "European champs.", active: true },
    { name: "West Ham United", country: "England", league: "Premier League", city: "London", lat: 51.5319, lon: 0.0394, founded: 1895, stadium: "London Stadium", trophies: 0, funFact: "Hammers’ move.", active: true },
    { name: "Everton", country: "England", league: "Premier League", city: "Liverpool", lat: 53.4388, lon: -2.9663, founded: 1878, stadium: "Goodison Park", trophies: 9, funFact: "Toffees’ grit.", active: true },
    { name: "Brighton & Hove Albion", country: "England", league: "Premier League", city: "Brighton", lat: 50.8294, lon: -0.1391, founded: 1901, stadium: "Amex Stadium", trophies: 0, funFact: "Seagulls soaring.", active: true },
    { name: "Wolverhampton Wanderers", country: "England", league: "Premier League", city: "Wolverhampton", lat: 52.5902, lon: -2.1305, founded: 1877, stadium: "Molineux", trophies: 3, funFact: "Wolves’ pack.", active: true },
    { name: "Crystal Palace", country: "England", league: "Premier League", city: "London", lat: 51.3983, lon: -0.0855, founded: 1905, stadium: "Selhurst Park", trophies: 0, funFact: "Eagles of London.", active: true },
    { name: "Brentford", country: "England", league: "Premier League", city: "London", lat: 51.4882, lon: -0.3048, founded: 1889, stadium: "Gtech Community Stadium", trophies: 0, funFact: "Bees buzzing.", active: true },
    { name: "Nottingham Forest", country: "England", league: "Premier League", city: "Nottingham", lat: 52.9400, lon: -1.1370, founded: 1865, stadium: "City Ground", trophies: 1, funFact: "European kings.", active: true },
    { name: "Bournemouth", country: "England", league: "Premier League", city: "Bournemouth", lat: 50.7352, lon: -1.8380, founded: 1899, stadium: "Vitality Stadium", trophies: 0, funFact: "Cherries’ rise.", active: true },
    { name: "Fulham", country: "England", league: "Premier League", city: "London", lat: 51.4750, lon: -0.2216, founded: 1879, stadium: "Craven Cottage", trophies: 0, funFact: "Riverside charm.", active: true },
    { name: "Southampton", country: "England", league: "Premier League", city: "Southampton", lat: 50.9059, lon: -1.3910, founded: 1885, stadium: "St Mary’s", trophies: 0, funFact: "Saints’ revival.", active: true },
    { name: "Leicester City", country: "England", league: "Premier League", city: "Leicester", lat: 52.6203, lon: -1.1422, founded: 1884, stadium: "King Power Stadium", trophies: 1, funFact: "Miracle champs.", active: true },
    { name: "Ipswich Town", country: "England", league: "Premier League", city: "Ipswich", lat: 52.0550, lon: 1.1450, founded: 1878, stadium: "Portman Road", trophies: 1, funFact: "Tractor Boys.", active: true },

    // Italy - Serie A (20)
    { name: "Juventus", country: "Italy", league: "Serie A", city: "Turin", lat: 45.0703, lon: 7.6869, founded: 1897, stadium: "Allianz Stadium", trophies: 36, funFact: "Old Lady’s reign.", active: true },
    { name: "Inter Milan", country: "Italy", league: "Serie A", city: "Milan", lat: 45.4780, lon: 9.1240, founded: 1908, stadium: "San Siro", trophies: 19, funFact: "Nerazzurri power.", active: true },
    { name: "AC Milan", country: "Italy", league: "Serie A", city: "Milan", lat: 45.4780, lon: 9.1240, founded: 1899, stadium: "San Siro", trophies: 19, funFact: "Rossoneri resurgence.", active: true },
    { name: "Napoli", country: "Italy", league: "Serie A", city: "Naples", lat: 40.8518, lon: 14.2681, founded: 1926, stadium: "Diego Armando Maradona", trophies: 3, funFact: "Maradona’s legacy.", active: true },
    { name: "AS Roma", country: "Italy", league: "Serie A", city: "Rome", lat: 41.9339, lon: 12.4663, founded: 1927, stadium: "Stadio Olimpico", trophies: 3, funFact: "Giallorossi heart.", active: true },
    { name: "Lazio", country: "Italy", league: "Serie A", city: "Rome", lat: 41.9339, lon: 12.4663, founded: 1900, stadium: "Stadio Olimpico", trophies: 2, funFact: "Biancocelesti grit.", active: true },
    { name: "Atalanta", country: "Italy", league: "Serie A", city: "Bergamo", lat: 45.6983, lon: 9.6773, founded: 1907, stadium: "Gewiss Stadium", trophies: 0, funFact: "Overachieving gods.", active: true },
    { name: "Fiorentina", country: "Italy", league: "Serie A", city: "Florence", lat: 43.7696, lon: 11.2558, founded: 1926, stadium: "Artemio Franchi", trophies: 2, funFact: "Viola flair.", active: true },
    { name: "Torino", country: "Italy", league: "Serie A", city: "Turin", lat: 45.0703, lon: 7.6869, founded: 1906, stadium: "Stadio Olimpico Grande Torino", trophies: 7, funFact: "Granata history.", active: true },
    { name: "Bologna", country: "Italy", league: "Serie A", city: "Bologna", lat: 44.4949, lon: 11.3426, founded: 1909, stadium: "Renato Dall’Ara", trophies: 7, funFact: "Rossoblu resurgence.", active: true },
    { name: "Udinese", country: "Italy", league: "Serie A", city: "Udine", lat: 46.0666, lon: 13.2357, founded: 1896, stadium: "Dacia Arena", trophies: 0, funFact: "Friuli’s finest.", active: true },
    { name: "Sassuolo", country: "Italy", league: "Serie A", city: "Sassuolo", lat: 44.5445, lon: 10.7848, founded: 1920, stadium: "Mapei Stadium", trophies: 0, funFact: "Neroverdi surprise.", active: true },
    { name: "Empoli", country: "Italy", league: "Serie A", city: "Empoli", lat: 43.7179, lon: 10.9476, founded: 1920, stadium: "Carlo Castellani", trophies: 0, funFact: "Azzurri battlers.", active: true },
    { name: "Genoa", country: "Italy", league: "Serie A", city: "Genoa", lat: 44.4056, lon: 8.9463, founded: 1893, stadium: "Luigi Ferraris", trophies: 9, funFact: "Oldest Italian club.", active: true },
    { name: "Cagliari", country: "Italy", league: "Serie A", city: "Cagliari", lat: 39.2238, lon: 9.1217, founded: 1920, stadium: "Unipol Domus", trophies: 1, funFact: "Sardinia’s champs.", active: true },
    { name: "Hellas Verona", country: "Italy", league: "Serie A", city: "Verona", lat: 45.4384, lon: 10.9916, founded: 1903, stadium: "Marcantonio Bentegodi", trophies: 1, funFact: "1985 miracle.", active: true },
    { name: "Parma", country: "Italy", league: "Serie A", city: "Parma", lat: 44.8015, lon: 10.3280, founded: 1913, stadium: "Ennio Tardini", trophies: 0, funFact: "Crociati comeback.", active: true },
    { name: "Monza", country: "Italy", league: "Serie A", city: "Monza", lat: 45.5845, lon: 9.2749, founded: 1912, stadium: "U-Power Stadium", trophies: 0, funFact: "Berlusconi’s dream.", active: true },
    { name: "Como", country: "Italy", league: "Serie A", city: "Como", lat: 45.8081, lon: 9.0852, founded: 1907, stadium: "Giuseppe Sinigaglia", trophies: 0, funFact: "Lakeside rise.", active: true },
    { name: "Lecce", country: "Italy", league: "Serie A", city: "Lecce", lat: 40.3515, lon: 18.1750, founded: 1908, stadium: "Via del Mare", trophies: 0, funFact: "Salento’s warriors.", active: true },

    // Brazil - Serie A (20)
    { name: "Flamengo", country: "Brazil", league: "Serie A", city: "Rio de Janeiro", lat: -22.9083, lon: -43.1964, founded: 1895, stadium: "Maracana", trophies: 8, funFact: "Most popular club.", active: true },
    { name: "Palmeiras", country: "Brazil", league: "Serie A", city: "Sao Paulo", lat: -23.5489, lon: -46.6388, founded: 1914, stadium: "Allianz Parque", trophies: 11, funFact: "First World champs.", active: true },
    { name: "Santos FC", country: "Brazil", league: "Serie A", city: "Santos", lat: -23.5505, lon: -46.6333, founded: 1912, stadium: "Vila Belmiro", trophies: 9, funFact: "Pele’s home club.", active: true },
    { name: "Corinthians", country: "Brazil", league: "Serie A", city: "Sao Paulo", lat: -23.5453, lon: -46.4731, founded: 1910, stadium: "Neo Quimica Arena", trophies: 7, funFact: "Timão’s faithful.", active: true },
    { name: "Sao Paulo", country: "Brazil", league: "Serie A", city: "Sao Paulo", lat: -23.5489, lon: -46.6388, founded: 1930, stadium: "Morumbi", trophies: 6, funFact: "Three-time world champs.", active: true },
    { name: "Fluminense", country: "Brazil", league: "Serie A", city: "Rio de Janeiro", lat: -22.9110, lon: -43.1729, founded: 1902, stadium: "Maracana", trophies: 4, funFact: "Tricolor elegance.", active: true },
    { name: "Gremio", country: "Brazil", league: "Serie A", city: "Porto Alegre", lat: -30.0346, lon: -51.2177, founded: 1903, stadium: "Arena do Gremio", trophies: 2, funFact: "Imortal Tricolor.", active: true },
    { name: "Internacional", country: "Brazil", league: "Serie A", city: "Porto Alegre", lat: -30.0655, lon: -51.2350, founded: 1909, stadium: "Beira-Rio", trophies: 3, funFact: "Colorado giants.", active: true },
    { name: "Atletico Mineiro", country: "Brazil", league: "Serie A", city: "Belo Horizonte", lat: -19.9173, lon: -43.9345, founded: 1908, stadium: "Arena MRV", trophies: 2, funFact: "Galo’s roar.", active: true },
    { name: "Cruzeiro", country: "Brazil", league: "Serie A", city: "Belo Horizonte", lat: -19.9208, lon: -43.9378, founded: 1921, stadium: "Mineirao", trophies: 4, funFact: "Raposa’s revival.", active: true },
    { name: "Botafogo", country: "Brazil", league: "Serie A", city: "Rio de Janeiro", lat: -22.9519, lon: -43.1750, founded: 1904, stadium: "Nilton Santos", trophies: 2, funFact: "Lone Star shine.", active: true },
    { name: "Vasco da Gama", country: "Brazil", league: "Serie A", city: "Rio de Janeiro", lat: -22.8908, lon: -43.2280, founded: 1898, stadium: "Sao Januario", trophies: 4, funFact: "Cross of Malta.", active: true },
    { name: "Bahia", country: "Brazil", league: "Serie A", city: "Salvador", lat: -12.9714, lon: -38.5014, founded: 1931, stadium: "Arena Fonte Nova", trophies: 2, funFact: "Tricolor de Aço.", active: true },
    { name: "Athletico Paranaense", country: "Brazil", league: "Serie A", city: "Curitiba", lat: -25.4489, lon: -49.3044, founded: 1924, stadium: "Arena da Baixada", trophies: 1, funFact: "Furacão force.", active: true },
    { name: "Fortaleza", country: "Brazil", league: "Serie A", city: "Fortaleza", lat: -3.7327, lon: -38.5270, founded: 1918, stadium: "Castelao", trophies: 0, funFact: "Lion of the North.", active: true },
    { name: "Bragantino", country: "Brazil", league: "Serie A", city: "Braganca Paulista", lat: -22.9520, lon: -46.5419, founded: 1928, stadium: "Nabi Abi Chedid", trophies: 0, funFact: "Red Bull boost.", active: true },
    { name: "Cuiaba", country: "Brazil", league: "Serie A", city: "Cuiaba", lat: -15.5989, lon: -56.0949, founded: 2001, stadium: "Arena Pantanal", trophies: 0, funFact: "Golden Dourado.", active: true },
    { name: "Vitoria", country: "Brazil", league: "Serie A", city: "Salvador", lat: -12.9714, lon: -38.5014, founded: 1899, stadium: "Barradao", trophies: 0, funFact: "Red and black.", active: true },
    { name: "Atletico Goianiense", country: "Brazil", league: "Serie A", city: "Goiania", lat: -16.6869, lon: -49.2648, founded: 1937, stadium: "Antonio Accioly", trophies: 0, funFact: "Dragon’s fight.", active: true },
    { name: "Juventude", country: "Brazil", league: "Serie A", city: "Caxias do Sul", lat: -29.1681, lon: -51.1794, founded: 1913, stadium: "Alfredo Jaconi", trophies: 0, funFact: "Green comeback.", active: true },

    // Argentina - Primera División (28)
    { name: "River Plate", country: "Argentina", league: "Primera División", city: "Buenos Aires", lat: -34.5453, lon: -58.4498, founded: 1901, stadium: "Monumental", trophies: 38, funFact: "Millionaires’ glory.", active: true },
    { name: "Boca Juniors", country: "Argentina", league: "Primera División", city: "Buenos Aires", lat: -34.6357, lon: -58.3646, founded: 1905, stadium: "La Bombonera", trophies: 35, funFact: "Xeneizes’ passion.", active: true },
    { name: "Independiente", country: "Argentina", league: "Primera División", city: "Avellaneda", lat: -34.6703, lon: -58.3712, founded: 1905, stadium: "Libertadores de America", trophies: 16, funFact: "Red Devils.", active: true },
    { name: "Racing Club", country: "Argentina", league: "Primera División", city: "Avellaneda", lat: -34.6675, lon: -58.3685, founded: 1903, stadium: "El Cilindro", trophies: 18, funFact: "The Academy.", active: true },
    { name: "San Lorenzo", country: "Argentina", league: "Primera División", city: "Buenos Aires", lat: -34.6372, lon: -58.4023, founded: 1908, stadium: "Pedro Bidegain", trophies: 15, funFact: "Pope’s team.", active: true },
    { name: "Velez Sarsfield", country: "Argentina", league: "Primera División", city: "Buenos Aires", lat: -34.6337, lon: -58.5206, founded: 1910, stadium: "Jose Amalfitani", trophies: 10, funFact: "El Fortin.", active: true },
    { name: "Estudiantes", country: "Argentina", league: "Primera División", city: "La Plata", lat: -34.9137, lon: -57.9418, founded: 1905, stadium: "Jorge Luis Hirschi", trophies: 6, funFact: "Pincha’s pride.", active: true },
    { name: "Newell’s Old Boys", country: "Argentina", league: "Primera División", city: "Rosario", lat: -32.9442, lon: -60.6505, founded: 1903, stadium: "Marcelo Bielsa", trophies: 6, funFact: "Messi’s youth.", active: true },
    { name: "Rosario Central", country: "Argentina", league: "Primera División", city: "Rosario", lat: -32.9477, lon: -60.6305, founded: 1889, stadium: "Gigante de Arroyito", trophies: 4, funFact: "Canallas’ spirit.", active: true },
    { name: "Argentinos Juniors", country: "Argentina", league: "Primera División", city: "Buenos Aires", lat: -34.6076, lon: -58.4633, founded: 1904, stadium: "Diego Armando Maradona", trophies: 3, funFact: "Maradona’s start.", active: true },
    { name: "Lanús", country: "Argentina", league: "Primera División", city: "Lanús", lat: -34.7145, lon: -58.3950, founded: 1915, stadium: "Ciudad de Lanús", trophies: 2, funFact: "Granate grit.", active: true },
    { name: "Huracán", country: "Argentina", league: "Primera División", city: "Buenos Aires", lat: -34.6433, lon: -58.3985, founded: 1908, stadium: "Tomás Adolfo Ducó", trophies: 5, funFact: "Globo’s flair.", active: true },
    { name: "Gimnasia La Plata", country: "Argentina", league: "Primera División", city: "La Plata", lat: -34.9215, lon: -57.9545, founded: 1887, stadium: "Juan Carmelo Zerillo", trophies: 0, funFact: "El Lobo’s howl.", active: true },
    { name: "Talleres", country: "Argentina", league: "Primera División", city: "Córdoba", lat: -31.4201, lon: -64.1888, founded: 1913, stadium: "Mario Alberto Kempes", trophies: 0, funFact: "La T’s rise.", active: true },
    { name: "Defensa y Justicia", country: "Argentina", league: "Primera División", city: "Florencio Varela", lat: -34.8217, lon: -58.2786, founded: 1935, stadium: "Norberto Tomaghello", trophies: 0, funFact: "Halcón surprise.", active: true },
    { name: "Godoy Cruz", country: "Argentina", league: "Primera División", city: "Mendoza", lat: -32.8895, lon: -68.8458, founded: 1921, stadium: "Malvinas Argentinas", trophies: 0, funFact: "Tomba tenacity.", active: true },
    { name: "Unión", country: "Argentina", league: "Primera División", city: "Santa Fe", lat: -31.6107, lon: -60.6973, founded: 1907, stadium: "15 de Abril", trophies: 0, funFact: "Tatengue spirit.", active: true },
    { name: "Banfield", country: "Argentina", league: "Primera División", city: "Banfield", lat: -34.7435, lon: -58.3965, founded: 1896, stadium: "Florencio Sola", trophies: 1, funFact: "El Taladro.", active: true },
    { name: "Platense", country: "Argentina", league: "Primera División", city: "Buenos Aires", lat: -34.5930, lon: -58.4975, founded: 1905, stadium: "Ciudad de Vicente López", trophies: 0, funFact: "Calamar comeback.", active: true },
    { name: "Belgrano", country: "Argentina", league: "Primera División", city: "Córdoba", lat: -31.4135, lon: -64.1892, founded: 1905, stadium: "Julio César Villagra", trophies: 0, funFact: "Pirata power.", active: true },
    { name: "Tigre", country: "Argentina", league: "Primera División", city: "Victoria", lat: -34.4470, lon: -58.5570, founded: 1902, stadium: "José Dellagiovanna", trophies: 0, funFact: "Matadores’ roar.", active: true },
    { name: "Central Córdoba", country: "Argentina", league: "Primera División", city: "Santiago del Estero", lat: -27.7834, lon: -64.2642, founded: 1919, stadium: "Alfredo Terrera", trophies: 0, funFact: "Ferroviario fight.", active: true },
    { name: "Sarmiento", country: "Argentina", league: "Primera División", city: "Junín", lat: -34.5857, lon: -60.9496, founded: 1911, stadium: "Eva Perón", trophies: 0, funFact: "Verde resilience.", active: true },
    { name: "Atlético Tucumán", country: "Argentina", league: "Primera División", city: "San Miguel de Tucumán", lat: -26.8083, lon: -65.2176, founded: 1902, stadium: "Monumental José Fierro", trophies: 0, funFact: "Decano’s spirit.", active: true },
    { name: "Instituto", country: "Argentina", league: "Primera División", city: "Córdoba", lat: -31.3914, lon: -64.2093, founded: 1918, stadium: "Juan Domingo Perón", trophies: 0, funFact: "La Gloria’s return.", active: true },
    { name: "Barracas Central", country: "Argentina", league: "Primera División", city: "Buenos Aires", lat: -34.6498, lon: -58.3830, founded: 1904, stadium: "Claudio Chiqui Tapia", trophies: 0, funFact: "Guapo grit.", active: true },
    { name: "Riestra", country: "Argentina", league: "Primera División", city: "Buenos Aires", lat: -34.6680, lon: -58.4268, founded: 1931, stadium: "Guillermo Laza", trophies: 0, funFact: "Blanquinegro battlers.", active: true },
    { name: "Deportivo Riestra", country: "Argentina", league: "Primera División", city: "Buenos Aires", lat: -34.6680, lon: -58.4268, founded: 1931, stadium: "Guillermo Laza", trophies: 0, funFact: "New kids on the block.", active: true },

    // Germany - Bundesliga (18)
    { name: "Bayern Munich", country: "Germany", league: "Bundesliga", city: "Munich", lat: 48.1372, lon: 11.5755, founded: 1900, stadium: "Allianz Arena", trophies: 33, funFact: "Bavarian dominance.", active: true },
    { name: "Borussia Dortmund", country: "Germany", league: "Bundesliga", city: "Dortmund", lat: 51.5136, lon: 7.4653, founded: 1909, stadium: "Signal Iduna Park", trophies: 8, funFact: "Yellow Wall.", active: true },
    { name: "RB Leipzig", country: "Germany", league: "Bundesliga", city: "Leipzig", lat: 51.3397, lon: 12.3731, founded: 2009, stadium: "Red Bull Arena", trophies: 0, funFact: "Red Bull rise.", active: true },
    { name: "Bayer Leverkusen", country: "Germany", league: "Bundesliga", city: "Leverkusen", lat: 51.0406, lon: 7.0023, founded: 1904, stadium: "BayArena", trophies: 1, funFact: "Neverkusen no more.", active: true },
    { name: "Borussia Mönchengladbach", country: "Germany", league: "Bundesliga", city: "Mönchengladbach", lat: 51.1747, lon: 6.3853, founded: 1900, stadium: "Borussia-Park", trophies: 5, funFact: "Foals’ flair.", active: true },
    { name: "VfB Stuttgart", country: "Germany", league: "Bundesliga", city: "Stuttgart", lat: 48.7836, lon: 9.1829, founded: 1893, stadium: "Mercedes-Benz Arena", trophies: 5, funFact: "Swabian resurgence.", active: true },
    { name: "Eintracht Frankfurt", country: "Germany", league: "Bundesliga", city: "Frankfurt", lat: 50.1109, lon: 8.6821, founded: 1899, stadium: "Deutsche Bank Park", trophies: 1, funFact: "Eagles’ flight.", active: true },
    { name: "Wolfsburg", country: "Germany", league: "Bundesliga", city: "Wolfsburg", lat: 52.4226, lon: 10.7865, founded: 1945, stadium: "Volkswagen Arena", trophies: 1, funFact: "Wolves’ howl.", active: true },
    { name: "Freiburg", country: "Germany", league: "Bundesliga", city: "Freiburg", lat: 47.9990, lon: 7.8421, founded: 1904, stadium: "Europa-Park Stadion", trophies: 0, funFact: "Black Forest battlers.", active: true },
    { name: "Hoffenheim", country: "Germany", league: "Bundesliga", city: "Sinsheim", lat: 49.2529, lon: 8.8870, founded: 1899, stadium: "PreZero Arena", trophies: 0, funFact: "Village giants.", active: true },
    { name: "Mainz 05", country: "Germany", league: "Bundesliga", city: "Mainz", lat: 49.9929, lon: 8.2473, founded: 1905, stadium: "Mewa Arena", trophies: 0, funFact: "Carnival club.", active: true },
    { name: "Werder Bremen", country: "Germany", league: "Bundesliga", city: "Bremen", lat: 53.0793, lon: 8.8017, founded: 1899, stadium: "Weserstadion", trophies: 4, funFact: "Green-White return.", active: true },
    { name: "Augsburg", country: "Germany", league: "Bundesliga", city: "Augsburg", lat: 48.3705, lon: 10.8978, founded: 1907, stadium: "WWK Arena", trophies: 0, funFact: "Fuggerstadt fighters.", active: true },
    { name: "Union Berlin", country: "Germany", league: "Bundesliga", city: "Berlin", lat: 52.5145, lon: 13.2395, founded: 1966, stadium: "Stadion An der Alten Försterei", trophies: 0, funFact: "Eisern Union.", active: true },
    { name: "Bochum", country: "Germany", league: "Bundesliga", city: "Bochum", lat: 51.4818, lon: 7.2162, founded: 1848, stadium: "Vonovia Ruhrstadion", trophies: 0, funFact: "Blue-White battlers.", active: true },
    { name: "Heidenheim", country: "Germany", league: "Bundesliga", city: "Heidenheim", lat: 48.6766, lon: 10.1516, founded: 1846, stadium: "Voith-Arena", trophies: 0, funFact: "Small-town surprise.", active: true },
    { name: "Holstein Kiel", country: "Germany", league: "Bundesliga", city: "Kiel", lat: 54.3233, lon: 10.1228, founded: 1900, stadium: "Holstein-Stadion", trophies: 0, funFact: "Storks’ ascent.", active: true },
    { name: "St. Pauli", country: "Germany", league: "Bundesliga", city: "Hamburg", lat: 53.5544, lon: 9.9637, founded: 1910, stadium: "Millerntor-Stadion", trophies: 0, funFact: "Pirate pride.", active: true },

    // Portugal - Primeira Liga (18)
    { name: "Benfica", country: "Portugal", league: "Primeira Liga", city: "Lisbon", lat: 38.7528, lon: -9.1845, founded: 1904, stadium: "Estadio da Luz", trophies: 38, funFact: "Eagles’ dominance.", active: true },
    { name: "Porto", country: "Portugal", league: "Primeira Liga", city: "Porto", lat: 41.1618, lon: -8.5839, founded: 1893, stadium: "Estadio do Dragao", trophies: 30, funFact: "Dragons’ roar.", active: true },
    { name: "Sporting CP", country: "Portugal", league: "Primeira Liga", city: "Lisbon", lat: 38.7611, lon: -9.1608, founded: 1906, stadium: "Jose Alvalade", trophies: 20, funFact: "Lions’ resurgence.", active: true },
    { name: "Braga", country: "Portugal", league: "Primeira Liga", city: "Braga", lat: 41.5454, lon: -8.4205, founded: 1921, stadium: "Estadio Municipal de Braga", trophies: 0, funFact: "Arsenalistas’ fight.", active: true },
    { name: "Vitoria Guimaraes", country: "Portugal", league: "Primeira Liga", city: "Guimaraes", lat: 41.4425, lon: -8.2950, founded: 1922, stadium: "Dom Afonso Henriques", trophies: 0, funFact: "Conquerors’ spirit.", active: true },
    { name: "Famalicão", country: "Portugal", league: "Primeira Liga", city: "Vila Nova de Famalicão", lat: 41.4075, lon: -8.5198, founded: 1931, stadium: "Estadio Municipal", trophies: 0, funFact: "Famalicão’s rise.", active: true },
    { name: "Moreirense", country: "Portugal", league: "Primeira Liga", city: "Moreira de Cónegos", lat: 41.3859, lon: -8.3418, founded: 1938, stadium: "Parque Joaquim de Almeida Freitas", trophies: 0, funFact: "Verde return.", active: true },
    { name: "Gil Vicente", country: "Portugal", league: "Primeira Liga", city: "Barcelos", lat: 41.5317, lon: -8.6180, founded: 1924, stadium: "Estadio Cidade de Barcelos", trophies: 0, funFact: "Roosters’ pluck.", active: true },
    { name: "Boavista", country: "Portugal", league: "Primeira Liga", city: "Porto", lat: 41.1621, lon: -8.6425, founded: 1903, stadium: "Estadio do Bessa", trophies: 1, funFact: "Checkered past.", active: true },
    { name: "Santa Clara", country: "Portugal", league: "Primeira Liga", city: "Ponta Delgada", lat: 37.7412, lon: -25.6756, founded: 1927, stadium: "Estadio de Sao Miguel", trophies: 0, funFact: "Azores’ pride.", active: true },
    { name: "Estoril", country: "Portugal", league: "Primeira Liga", city: "Estoril", lat: 38.7060, lon: -9.3979, founded: 1939, stadium: "Estadio Antonio Coimbra da Mota", trophies: 0, funFact: "Canaries’ flight.", active: true },
    { name: "Arouca", country: "Portugal", league: "Primeira Liga", city: "Arouca", lat: 40.9312, lon: -8.2450, founded: 1951, stadium: "Estadio Municipal de Arouca", trophies: 0, funFact: "Small-town grit.", active: true },
    { name: "Rio Ave", country: "Portugal", league: "Primeira Liga", city: "Vila do Conde", lat: 41.3006, lon: -8.7362, founded: 1939, stadium: "Estadio dos Arcos", trophies: 0, funFact: "River warriors.", active: true },
    { name: "Casa Pia", country: "Portugal", league: "Primeira Liga", city: "Lisbon", lat: 38.7369, lon: -9.1393, founded: 1920, stadium: "Estadio Pina Manique", trophies: 0, funFact: "Geese’s ascent.", active: true },
    { name: "Farense", country: "Portugal", league: "Primeira Liga", city: "Faro", lat: 37.0194, lon: -7.9307, founded: 1910, stadium: "Estadio de Sao Luis", trophies: 0, funFact: "Algarve’s lions.", active: true },
    { name: "AVS", country: "Portugal", league: "Primeira Liga", city: "Vila das Aves", lat: 41.3681, lon: -8.4103, founded: 2023, stadium: "Estadio do CD Aves", trophies: 0, funFact: "New kids on the block.", active: true },
    { name: "Estrela da Amadora", country: "Portugal", league: "Primeira Liga", city: "Amadora", lat: 38.7538, lon: -9.2308, founded: 1932, stadium: "Estadio Jose Gomes", trophies: 0, funFact: "Tricolor return.", active: true },
    { name: "Nacional", country: "Portugal", league: "Primeira Liga", city: "Funchal", lat: 32.6705, lon: -16.9241, founded: 1910, stadium: "Estadio da Madeira", trophies: 0, funFact: "Madeira’s finest.", active: true },

    // Lost Legends (3)
    { name: "Wimbledon FC", country: "England", league: "Premier League (historic)", city: "London", lat: 51.4216, lon: -0.2068, founded: 1889, stadium: "Plough Lane (old)", trophies: 0, funFact: "Crazy Gang’s FA Cup (1988).", active: false },
    { name: "Parma (old)", country: "Italy", league: "Serie A (historic)", city: "Parma", lat: 44.8015, lon: 10.3280, founded: 1913, stadium: "Ennio Tardini (old)", trophies: 3, funFact: "Bankrupt in 2015, reborn.", active: false },
    { name: "Sporting Toulon", country: "France", league: "Ligue 1 (historic)", city: "Toulon", lat: 43.1242, lon: 5.9280, founded: 1944, stadium: "Stade de Bon Rencontre", trophies: 0, funFact: "Merged and faded.", active: false }
];